import type { Recipe } from "./types";

export const KOOKBOOK_RECIPES_1: Recipe[] = [
  {
    id: "kb-1",
    slug: "chicken-stock",
    title: "Chicken Stock",
    description:
      "The source of everything. A proper chicken stock made in the InstaPot -- four hours of patience that pays off in every dish that follows.",
    category: "sauces-condiments",
    image: "",
    prepTime: 15,
    cookTime: 240,
    servings: 8,
    difficulty: "Easy",
    ingredients: [
      "1 whole chicken or a couple of chicken backs",
      "Celery, onion, carrot -- all finely chopped (mirepoix)",
      "Onion, coarsely chopped",
      "Bay leaves",
      "Salt",
      "Peppercorns",
    ],
    instructions: [
      "Create a nest of the mirepoix at the bottom of the pot. Place chicken or backs on the top.",
      "Cover with water (take it to the 2/3 mark on the side of the pot), add peppercorns, salt and bay leaves.",
      "Set the Broth setting to 2 hours.",
      "Let it cool down for another two hours. The longer the better.",
    ],
    contributedBy: "Poppie",
    story:
      "I can't tell you much on this matter because you do it anyhow. Sadly, for me it is the only real value in the InstaPot. But it is sufficiently important to merit its value. And for me it's all about time. Four hours is about right.",
    tags: ["stock", "base", "fundamental", "instapot", "chicken"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-2",
    slug: "beef-or-lamb-stock",
    title: "Beef or Lamb Stock",
    description:
      "Roasted bones make the richest stock. The fat that comes off is liquid gold -- use it as umami frying butter.",
    category: "sauces-condiments",
    image: "",
    prepTime: 15,
    cookTime: 300,
    servings: 8,
    difficulty: "Easy",
    ingredients: [
      "1 kg beef (or lamb) bones with a modicum of meat on them",
      "Onion, coarsely chopped",
      "A couple of cloves garlic, peeled",
      "Salt and pepper",
      "Celery, onion, carrot -- finely chopped (mirepoix)",
    ],
    instructions: [
      "Scatter the bones on a tray lined with tinfoil. That's just to save cleaning up an oily, stuck pan afterwards. Cut up an onion roughly and wedge between. Peel a couple of cloves of garlic and jam in as well. Season with salt and pepper, but don't drizzle with oil.",
      "Roast at 180C for 1 hour.",
      "Create a mirepoix nest in the pot and add the roasted bones and the marrow fat. Same process as chicken stock -- two hours on, two hours to rest.",
      "The immense amount of fat that is produced can be prised off and used as an umami frying butter when making a mince dish for example.",
    ],
    contributedBy: "Poppie",
    story:
      "I can't tell you much on this matter because you do it anyhow. Sadly, for me it is the only real value in the InstaPot. But it is sufficiently important to merit its value. And for me it's all about time. Four hours is about right.",
    tags: ["stock", "base", "fundamental", "beef", "lamb", "roasted-bones"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-3",
    slug: "chicken-soup",
    title: "Chicken Soup",
    description:
      "The natural next step after a good stock. Use the darker meat from the chicken -- the breast is pretty much tasteless by this point.",
    category: "soups",
    image: "",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "Leftover mirepoix (celery, onion, carrot), chopped",
      "Butter",
      "A little garlic, chopped",
      "Chicken stock",
      "Chicken from the stock pot, flaked (darker parts preferred)",
    ],
    instructions: [
      "Fry up the remaining mirepoix gently in some butter, add a little chopped up garlic.",
      "Add the stock and flake off the darker parts of the chicken. The breast can go in as well but it's pretty much tasteless at this point.",
      "Simmer until everything is heated through and the flavours have come together.",
    ],
    contributedBy: "Poppie",
    story:
      "For Asian countries, what makes any of these kinds of stock dishes is the fat on the top. That's where the flavour and mouthfeel really lies.",
    tags: ["soup", "chicken", "comfort-food", "simple", "stock"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-4",
    slug: "marcella-hazans-tomato-sauce",
    title: "Marcella Hazan's Tomato Sauce",
    description:
      "Three ingredients. One can of tomatoes, half an onion, and five tablespoons of butter. That's it. The basis for most tomato recipes.",
    category: "sauces-condiments",
    image: "",
    prepTime: 5,
    cookTime: 45,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "1 can of tomatoes",
      "1/2 onion, halved",
      "5 tablespoons of butter",
      "Salt to taste",
      "Basil (optional, if using immediately)",
    ],
    instructions: [
      "Place the tomatoes, butter, and halved onion in a medium saucepan (3 quarts or larger).",
      "Bring the sauce to a boil, then lower the heat to a simmer, and cook for 45 minutes, or until the butter drops separate from the tomato juices. Remove the onions and reserve for another use (perfect for making a bolognaise for example).",
      "Using an immersion blender, pulse a few times to break up large chunks of tomato. Season to taste if necessary. Basil can be added now if using it immediately.",
    ],
    contributedBy: "Poppie",
    story:
      "These are the fundamentals of everything that we do. The sauce, the gravy, the reduction, the jus or whatever pretentious name you want to call it is at the heart of my idea of food. It largely is the thing that we do after we have the stock done. Joan Harris used to say that the Fishes destroyed everything with gravy and look what happened to her. There are two kinds of people on the sauce spectrum. Those, like me, used to take a slice of bread after a good stew and cover it in butter and the remains of the pot. G wouldn't dream of it.\n\nI guess this is the easiest place to start. Three ingredients to make the basis for most tomato recipes.",
    tags: ["tomato", "sauce", "simple", "three-ingredient", "marcella-hazan"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-5",
    slug: "tanagra-tomato-sauce",
    title: "Tanagra Tomato Sauce",
    description:
      "Anette's slow-roasted tomato sauce from a small vineyard outside McGregor. Use it as a savoury jam, stir it into a bolognaise, or make it the base for cappuccino tomato soup.",
    category: "sauces-condiments",
    image: "",
    prepTime: 20,
    cookTime: 60,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "1 kg of ripe tomatoes (Roma if possible), cut into quarters",
      "1 head of garlic, with the top cut off, covered in olive oil and too much salt, wrapped in tinfoil",
      "1-2 onions, rough cut",
      "Fresh or dried rosemary",
      "1 cup of castor sugar",
      "Olive oil",
      "Salt and pepper",
    ],
    instructions: [
      "Place all the ingredients into an ovenproof bowl.",
      "Pour over the olive oil and top with the cup of castor sugar so that it looks like it's covered in a light dusting of snow.",
      "Cook at 180C for an hour. Remove and let cool.",
      "Find some idiot to pick through the cooled tomato and remove the skins. It's an awful job.",
      "If you're lucky you can use a small fork to remove the pieces of the roasted garlic into separate pieces. These have no end of purposes -- mash them into potato mash with parsley, use as a bed for bangers, or as a topping for a Poppie pie.",
    ],
    contributedBy: "Poppie",
    story:
      "Tanagra is a small vineyard that we stayed at just outside of McGregor. They were (and are) German and used to serve a continental breakfast which was the usual cold meats and pates. My favourite was a small bowl of tomatoes that you would literally treat as a savoury jam and spread on one of the home-made breads that she presented each morning. But it has endless uses. Mushed up a bit and added to a bolognaise it adds a juicy, sweet tomato taste and forms the base for the Morganster cappuccino tomato soup. So, this is Anette's tomato sauce.",
    tags: [
      "tomato",
      "sauce",
      "roasted",
      "tanagra",
      "mcgregor",
      "slow-roasted",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-6",
    slug: "matt-prestons-mayo",
    title: "Matt Preston's Mayo",
    description:
      "Homemade mayo that feels like watching an alchemical miracle happening before your eyes. Stick blender magic.",
    category: "sauces-condiments",
    image: "",
    prepTime: 10,
    cookTime: 0,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "1 egg",
      "1 tablespoon Dijon mustard",
      "A pinch of salt",
      "Juice of half a lemon",
      "350ml grapeseed oil",
    ],
    instructions: [
      "Carefully crack an egg into the base of a stick blender canister, making sure the yolk doesn't break. Add 1 tablespoon Dijon mustard, a pinch of salt and the juice of half a lemon.",
      "Gently pour in 350ml grapeseed oil, again taking care not to break the yolk.",
      "Insert the stick blender, making sure the blades completely cover the yolk. Blend.",
      "After a second or so you'll see white ribbons of mayo forming around the stick blender head. Now slowly pull the blender up through the oil so the mayo comes together.",
      "Taste. Season with more lemon juice and salt as required (and I suspect it will be required). Then push the blender back down through the mayo to incorporate all the oil.",
    ],
    contributedBy: "Poppie",
    story:
      "I know that Dylan has struggles with this, but it's like watching an alchemical miracle happening before your eyes.\n\nFor a variation, try the salsa verde mayonnaise: Blitz a garlic clove with a bunch of parsley (thin stalks and leaves), half a bunch of basil leaves, 1 tablespoon capers, six anchovy fillets and 100ml olive oil. Continue until it's a smooth puree. Add to the already made mayo.",
    tags: ["mayo", "mayonnaise", "condiment", "matt-preston", "homemade"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-7",
    slug: "tartar-sauce",
    title: "Tartar Sauce",
    description:
      "Poppie's take on the usual tartar. Capers, gherkin and chilli chopped to almost a mush and stirred through mayo with lemon juice.",
    category: "sauces-condiments",
    image: "",
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "1 cup mayonnaise",
      "15 small capers",
      "1 pickled gherkin, finely sliced (about 5 slices)",
      "1 pickled jalapeno or any chilli",
      "Juice of half a lemon",
      "Salt",
    ],
    instructions: [
      "Chop capers, gherkin and chilli up until they are almost a mush.",
      "Add to a bowl of mayo.",
      "Incorporate and add lemon juice. Season with salt.",
    ],
    contributedBy: "Poppie",
    story: "",
    tags: ["tartar", "sauce", "condiment", "fish", "seafood"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-8",
    slug: "lemon-butter-sauce",
    title: "Lemon Butter Sauce",
    description:
      "The sauce that accompanied sole on those standing Wednesday night dinners with Colin and Shirley. Also the sauce for gammon and asparagus.",
    category: "sauces-condiments",
    image: "",
    prepTime: 5,
    cookTime: 10,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "Juice of two lemons",
      "2 tablespoons of butter",
      "100ml whipping cream",
      "Bunch of chopped parsley, no stalks",
      "Salt",
    ],
    instructions: [
      "Over a medium heat, dissolve the butter.",
      "Add the lemon juice and stir to incorporate. Leave for a couple of minutes.",
      "Add the cream and stir to ensure that the sauce doesn't split. Wait for it to start to thicken and then reduce the heat.",
      "Add chopped parsley just before serving.",
    ],
    contributedBy: "Poppie",
    story:
      "At one stage, we ended up with a standing date with Colin and Shirley every Wednesday night. It went on for years. Colin was there for the fish. Shirls for the arguments with him. Often he bought the fish but after the debacle with a St Josephs (Shark) he brought, we took to buying the evening meal. They had a distinct liking for sole and this was the sauce that accompanied it. It's also the sauce that accompanies the gammon and asparagus recipe.",
    tags: ["sauce", "lemon", "butter", "cream", "fish", "sole"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-9",
    slug: "chicken-beef-lamb-gravy",
    title: "Chicken / Beef / Lamb Gravy",
    description:
      "More of a realisation than a method. The trivet trick that stops soggy bottoms and gives you the best base for gravy you've ever had.",
    category: "sauces-condiments",
    image: "",
    prepTime: 5,
    cookTime: 15,
    servings: 6,
    difficulty: "Easy",
    ingredients: [
      "Pan drippings from roast (chicken, beef, or lamb)",
      "1 cup stock (matching the meat)",
      "A splash of water",
      "A bit of flour or Bisto to thicken",
      "2 tablespoons tomato sauce (optional, for chicken or beef gravy)",
    ],
    instructions: [
      "Place the roast on a trivet (you can use the one that came with the InstaPot). Cover the base of the pan with a cup of stock and a splash of water. This keeps the roast moist and gives the best base for the gravy.",
      "After roasting the meat, remove and cover. Take the pan to the stove and use the liquid to scrape down the sides, loosening all the congealed goodness.",
      "Add extra stock if necessary. Once it's all incorporated, add a bit of flour or Bisto to thicken.",
      "If it's chicken or beef gravy, 2 tablespoons of tomato sauce makes a world of difference. But you mustn't be able to taste it in the final product.",
    ],
    contributedBy: "Poppie",
    story:
      "During lockdown, we would end up cooking some kind of roast and then spend hours afterward trying to get rid of the stubborn barnacles of congealed meat off the bottom of the pot. It also became evident that 80% of the taste lay in that stubborn coagulation. So to stop the fact that the chicken had a horrible soggy bottom where it had sat in the pan, I started using a trivet for all roasts. There's a couple of exceptions -- 100 pieces of garlic chicken, for example, needs to roast in its sauce.",
    tags: ["gravy", "technique", "roast", "fundamental", "trivet"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-10",
    slug: "chakalaka",
    title: "Chakalaka",
    description:
      "A South African classic. Goes best with pap and boerewors. Poppie is under no illusions that either of you will ever make this, but just in case.",
    category: "sides-salads",
    image: "",
    prepTime: 15,
    cookTime: 25,
    servings: 6,
    difficulty: "Easy",
    ingredients: [
      "3 tablespoons sunflower oil",
      "1 onion, finely chopped",
      "2 cloves garlic, crushed",
      "50g ginger, finely grated",
      "2 tablespoons curry powder/masala",
      "1 red pepper, finely chopped",
      "1 yellow pepper, finely chopped",
      "5 large carrots, grated",
      "2 tablespoons tomato puree",
      "400g can chopped tomatoes",
      "400g can baked beans",
      "Salt and pepper to taste",
    ],
    instructions: [
      "In a pan over medium heat, add the oil. Then add onion and saute until translucent and softened.",
      "Add garlic, ginger and curry powder. Stir to combine. Add peppers. Cook for 2 minutes.",
      "Add carrots. Stir to combine and ensure they're coated in curry powder. Add tomatoes and tomato paste. Stir to combine.",
      "Cook mixture for 5-10 minutes. Mixture should be well combined and thickened slightly.",
      "Add baked beans. Simmer for 5 minutes. Remove from heat.",
      "Serve with pap and boerewors.",
    ],
    contributedBy: "Poppie",
    story:
      "I'm under no illusions that the two of you will ever make this, but just in case.",
    tags: [
      "south-african",
      "chakalaka",
      "side-dish",
      "braai",
      "pap",
      "boerewors",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-11",
    slug: "trinchado-portuguese-steak-gravy",
    title: "Trinchado / Portuguese Steak Gravy",
    description:
      "The sauce that makes both Trinchado and Portuguese Steak. A peri-peri, red wine and beef stock reduction -- you're working towards that burn with a tangy lemon finish.",
    category: "sauces-condiments",
    image: "",
    prepTime: 10,
    cookTime: 30,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "1 tablespoon of olive oil",
      "1 onion, roughly chopped",
      "3 cloves of garlic, chopped",
      "Fresh rosemary if available (or dried)",
      "2 cups beef stock",
      "2 cups red wine",
      "2 tablespoons peri-peri (depending on the kids)",
      "Juice of a lemon",
      "2 tablespoons of brown sugar",
      "Salt and pepper",
      "2 bay leaves",
      "2 tablespoons flour/Bisto",
    ],
    instructions: [
      "Over a medium heat, add the oil, the onions and garlic.",
      "After they have softened, add the rosemary, the stock, the bay leaves and the wine. And then the peri-peri and sugar.",
      "Add salt and pepper and lemon juice. Keep at a medium boil.",
      "For both dishes, you're going to need a bounty of sauce, so now you need to make a slurry using the red wine and flour which you will add to thicken it up a bit.",
      "Strain off all of this and return the liquid to the pot for the final stages.",
    ],
    contributedBy: "Poppie",
    story:
      "These are both made using the same sauce. Sadly I think you are going to struggle to find a decent peri peri sauce. I guess in the worst case you could try using the Habanero Tabasco -- it's not that hot and has a nice fruity base note. Ideally you're working towards that burn with a tangy lemon finish.",
    tags: [
      "sauce",
      "portuguese",
      "peri-peri",
      "trinchado",
      "red-wine",
      "beef-stock",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-12",
    slug: "trinchado",
    title: "Trinchado",
    description:
      "Poppie's original Trinchado that went viral on the early internet and ended up on the US Portuguese ambassador's table -- though by then it was completely unrecognisable.",
    category: "mains",
    image: "",
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "Olive oil",
      "1 kg fillet steak (rump or sirloin if fillet is too expensive), cut into spoon-sized cubes",
      "Black pepper",
      "3 bay leaves",
      "3/4 tin of black kalamata olives, de-pipped",
      "Bucket load of chips",
      "Trinchado gravy (see recipe)",
      "Chunks of bread for serving",
    ],
    instructions: [
      "Cube the steak, place into a bowl and sprinkle olive oil over it and lots of black pepper. Mix it through.",
      "Over a high heat, brown the steak cubes. You don't want them cooked through, just scalded. Remove.",
      "Add the Trinchado gravy from the pot and incorporate all the good bits from the browning. Add the bay leaves and olives. It will take about 5 minutes for the flavours to come together.",
      "Cut and deep fry the chips. Timing is crucial here. The chips must be almost ready before you return the steak to the pan.",
      "Return the steak making sure that it does not overcook in the juice. It should just get kissed by the sauce. Serve with chips, spoons (because it's closer to a peri-peri sauce with beef) and chunks of bread if you run out of chips.",
      "Don't run out of chips.",
    ],
    contributedBy: "Poppie",
    story:
      "This one has a convoluted backstory. In the early days of internet, I was looking for a decent Trinchado recipe and discovered that there weren't any. So, on one of the local sites I put up my version of the recipe. About a month later I was contacted by a New York chef called David Leite. He's still around. Anyway, he wanted to clarify a couple of things, specifically what I meant by 'rump'. I tried to explain in my ignorant way and he got it completely wrong. He ended up using chuck and served it to the US Portuguese ambassador who was deeply impressed.\n\nThings just went crazy after that, not that I knew anything. For the longest time if one googled my name, all you could find was my recipe, ascribed to me but becoming completely unrecognisable as it was interpreted by people, especially those claiming a Portuguese heritage. The one that now exists out there on the interwebs bears no similarity to mine.\n\nEven mine doesn't anymore. In the original I used to add onions and garlic to the dish, not any more. All of that happens at the sauce level.",
    tags: [
      "portuguese",
      "trinchado",
      "steak",
      "peri-peri",
      "chips",
      "family-famous",
    ],
    featured: true,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-13",
    slug: "portuguese-steak",
    title: "Portuguese Steak",
    description:
      "Steak, egg and chips done the Portuguese way. Uses the same Trinchado gravy but the steak stays whole and gets topped with a fried egg.",
    category: "mains",
    image: "",
    prepTime: 15,
    cookTime: 15,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "Olive oil",
      "1 kg fillet steak (rump or sirloin if fillet is too expensive), cut into sizeable steaks",
      "Black pepper",
      "3 bay leaves",
      "Bucket load of chips, cut in rounds",
      "Eggs to order",
      "Trinchado gravy (see recipe)",
    ],
    instructions: [
      "Cut the steaks, place into a bowl and sprinkle olive oil over them and lots of black pepper.",
      "Over a highish heat, cook the steak to your liking. Remove and place in tinfoil wrap to rest.",
      "Cut and deep fry the chips. Remember, these are rounds. Timing is crucial here as well. The chips must be almost ready before you fry the eggs.",
      "The steaks should have rested. Return any liquids to the sauce. Place steak on a plate and pour over the sauce. Top with egg and chips.",
    ],
    contributedBy: "Poppie",
    story:
      "Same sauce as the Trinchado, different presentation. The steak stays whole, gets rested properly, and the sauce is poured over the top. Egg on top, round chips on the side. Simple and perfect.",
    tags: ["portuguese", "steak", "egg", "chips", "peri-peri"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-14",
    slug: "reuben-rifles-chilli-ginger-syrup",
    title: "Reuben Rifle's Chilli & Ginger Syrup",
    description:
      "A syrup that became part of the household DNA, despite never being made with the meal it was intended for. We've only ever had it with Woolies crumbed prawns.",
    category: "sauces-condiments",
    image: "",
    prepTime: 10,
    cookTime: 20,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "2 palm sugar or 3/4 cup of white sugar",
      "500ml water",
      "4 long red chillies, seeded and cut into julienne strips",
      "1 large thumb of ginger, cut into strips",
      "250ml fish sauce",
      "250ml lime juice",
    ],
    instructions: [
      "Put the palm sugar into a saucepan with 2 cups of the water and boil.",
      "Add the chillies, ginger, fish sauce and lime juice and simmer, until it reduces and bubbles start to form on the liquid.",
      "You're looking for a syrup that can be spooned over whatever you're eating. DO NOT make this as is -- divide the fish sauce and lime juice quantities by 100. The original recipe amounts are a mistake.",
    ],
    contributedBy: "Poppie",
    story:
      "Another one that has become part of the DNA of the household and weirdly has never been made with the meal that was originally intended. It's supposed to be served with pork belly which is simmered in stock for 3 hours before being flash fried. We've only ever had it with Woolies crumbed prawns and it might be another tricky one that means you have to hunt for decent chillies (dried can be used at a push).\n\nBrenda asked for the recipe years ago -- she was having her boss over for a meal -- and I sent her the link. She followed the recipe exactly and the result was inedible and, I would imagine, very embarrassing. I put it down here exactly as it was written on the site. I'm sure you'll spot where the two fuck-ups occurred. Divide by 100.",
    tags: [
      "syrup",
      "chilli",
      "ginger",
      "sweet",
      "prawns",
      "reuben-rifle",
      "warning",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-15",
    slug: "cumberland-sauce",
    title: "Cumberland Sauce",
    description:
      "An old recipe card favourite. Citrus peel reduced with port and redcurrant jelly into a glossy syrup. Used to serve it with fried kasler and rotis.",
    category: "sauces-condiments",
    image: "",
    prepTime: 20,
    cookTime: 20,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "1 orange",
      "1 lemon",
      "1 cup white sugar, granulated",
      "1 thumb of ginger, grated",
      "1 cup cold water",
      "1/2 cup bought red currant jelly",
      "3 tablespoons port or marsala",
      "1 cinnamon stick",
    ],
    instructions: [
      "Fill a small saucepan with the cold water. Remove the peel of the orange and lemon in strips about an inch long. Trim off any white pith on the underside of the peel.",
      "Once all the peel has been cleaned of pith, cut it into strips as thin as a sheet of paper. Place them back into the cold water. Add the sugar and place over a high heat. When it comes to a boil, strain the mixture, and reserve the peel.",
      "Put the juice of the orange and the lemon juice into a small pan with grated fresh ginger and port and reduce over a medium heat for 4-5 minutes until syrupy.",
      "Add the red currant jelly, port and cinnamon stick in a small saucepan over a medium heat. Add the lemon and orange zest and cook until it is syrupy.",
    ],
    contributedBy: "Poppie",
    story:
      "This goes way back to a time where I thought recipe cards were cool and we had these little cards for each recipe. It's so retro, it's actually quite cool again. Anyhow we used to serve this sauce with fried kasler and rotis.",
    tags: [
      "sauce",
      "cumberland",
      "citrus",
      "port",
      "redcurrant",
      "retro",
      "kasler",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-16",
    slug: "monkeygland-sauce",
    title: "Monkeygland Sauce",
    description:
      "A sweet rush followed immediately by a vinegar tang. Mix in cheddar just before serving if you want to go crazy and make a cheesewiz burger.",
    category: "sauces-condiments",
    image: "",
    prepTime: 10,
    cookTime: 15,
    servings: 6,
    difficulty: "Easy",
    ingredients: [
      "1 onion, diced",
      "3 tablespoons Mrs Balls' chutney",
      "1 tablespoon Worcestershire sauce",
      "1 tablespoon white sugar",
      "3 tablespoons vinegar (the cheaper the better)",
      "2 cloves of garlic, diced",
      "1 tablespoon tomato sauce",
      "2 teaspoons of Tabasco sauce",
      "Salt and pepper",
    ],
    instructions: [
      "Sweat the onions and garlic down until soft.",
      "Add all the other ingredients except the sugar.",
      "The taste you are looking for is a sweet rush, followed immediately by the vinegar tang. It should be sweet enough without the addition of the sugar, but add if necessary.",
    ],
    contributedBy: "Poppie",
    story:
      "If you really want to go crazy, you can mix in cheddar cheese just before serving to make a cheesewiz burger.\n\nAnd apropos of nothing, this was our favourite burger during lockdown. Topless lamb burger with soft gorgonzola and monkeygland sauce beneath.",
    tags: [
      "sauce",
      "monkeygland",
      "south-african",
      "braai",
      "burger",
      "chutney",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-17",
    slug: "pampinon",
    title: "Pampinon",
    description:
      "An obscure recipe from the Kommetjie days, probably a version of a Pan bagnat. A loaded baguette pressed under a heavy book for an hour. Lunch made up of many snacks of the same thing.",
    category: "starters-snacks",
    image: "",
    prepTime: 45,
    cookTime: 0,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "1 baguette, crunchy on the outside but moist on the inside",
      "6 radishes, thinly sliced (must cover the length of the baguette)",
      "5 tomatoes, peeled and de-pipped (only the flesh)",
      "20 de-pitted black olives",
      "10 good quality anchovies (reduce depending on taste)",
      "4-6 cloves of garlic, thinly sliced (or made into a garlic butter spread)",
      "3 spring onions, sliced at an angle",
      "Extra virgin olive oil",
      "Salt and pepper",
      "Cling wrap",
    ],
    instructions: [
      "Do all the prep as listed. Slice radishes, make garlic paste (it is well worth it), go through the laborious process of de-skinning and de-pipping the tomatoes, cut the olives etc.",
      "Place the loaf on enough cling film that will allow it to be covered and carefully slice the loaf down the centre making sure not to cut all the way through.",
      "Drizzle the olive oil on both sides of the bread.",
      "Add the garlic, the olives, the anchovies, the tomatoes and the spring onions.",
      "Season with a little salt (anchovies will add most of the salt) and pepper.",
      "Tightly wrap the loaf with the cling film. Place under a heavy book -- in the early days we used a copy of Grey's Anatomy, the only book thick, heavy and large enough to cover the baguette. It needs about 1 hour like this.",
      "Uncover and slice into reasonably sized slices. The idea is that you would take one, finish and return again. This is a lunch made up of many snacks of the same thing.",
    ],
    contributedBy: "Poppie",
    story:
      "When I lived in Kommetjie, my friends used to come and stay for the weekend. Usually this meant Catherine and Murray. Catherine was into everything horror and experimenting with food. Her husband (to be) was deeply conservative, deeply overweight and died about 3 years ago. While exercising. His take on food was to find unheard of recipes, often from the Middle Ages and we used to replicate them. This mix of the esoteric and the invented was the thing that brought and held us together. I guess that was the first time I began to understand the deeply social thing that was food and cooking.\n\nWhen I moved up to Johannesburg, I arrived armed with lots of these kinds of recipes. And fired Lucy as a cook after the first night. We had roast chicken.\n\nThis recipe was one that I've never been able to find on Google. The story was that it was always eaten during a game of petanque. It's probably an obscure version of a Pan bagnat and has become more and more of G's recipe on account of the elaborate steps that go into the careful preparation.\n\nI think the best way is to make it once as it was intended and then you can use whatever you like: soft Brie and ham? The objective here is to create something that tastes like nothing else but the ratio of bread to filling is crucial. It needs to soak deeply into the bread and you don't want it too bready.",
    tags: [
      "sandwich",
      "baguette",
      "kommetjie",
      "pan-bagnat",
      "pressed",
      "lunch",
      "snack",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-18",
    slug: "quiche-lorraine",
    title: "Quiche Lorraine",
    description:
      "Floyd's quiche that Poppie and G made for an early Feldner event and nearly died at how rich it was. If making again, halve the cream and add a touch of milk.",
    category: "mains",
    image: "",
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "Shortcrust pastry for a quiche dish",
      "200g bacon lardons",
      "450ml double cream (or 225ml cream and 200ml milk for a lighter version)",
      "4 eggs",
      "100g gruyere cheese, grated",
      "Salt and pepper",
      "Fresh asparagus (for asparagus variation)",
    ],
    instructions: [
      "Line a quiche dish with shortcrust pastry and blind bake until lightly golden.",
      "Fry the bacon lardons until crisp. Scatter over the pastry base.",
      "Beat the eggs with the cream (or cream and milk mix). Season with salt and pepper.",
      "Pour the egg mixture over the bacon. Top with grated gruyere.",
      "Bake at 180C for 30-35 minutes until set and golden. The asparagus quiche is the same recipe with fresh asparagus replacing or supplementing the bacon.",
    ],
    contributedBy: "Poppie",
    story:
      "I guess that Floyd was one of my early heroes for the reason that his recipes were largely simple and great tasting. G and I once made this quiche for some early Feldner event and nearly died at how rich it was (450ml double cream). If I were to make it again, I'd halve the cream and add a touch (200ml) of milk. The asparagus quiche is the same recipe with fresh asparagus.\n\nFloyd's Veal with Mustard is included here as a bonus: Michael (Fish) once came to stay with me at Kommetjie, in the old house at the top of the hill. One night after watching Floyd on TV, I made his veal with mustard. Four veal schnitzels, salt and pan fry over high heat -- don't overcook, they should still have a little bit of give. Remove to keep warm. Add 1 tablespoon butter to the pan and then 2 tablespoons Dijon mustard. When they have come together add 200ml whipping cream and stir until it thickens. Return veal to pan and serve. It was that easy and with a green leaf salad to cut through the richness of the sauce, just right. Would also work with a plain uncrumbed pork or chicken schnitzel.",
    tags: ["quiche", "floyd", "pastry", "cream", "bacon", "asparagus"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-19",
    slug: "white-bean-puttanesca-with-garlic-bread",
    title: "White Bean Puttanesca with Garlic Bread",
    description:
      "A completely vegan dish, which is weird for this book. Serve hot in winter and cold in summer. The flavours grow more intense over the next two days.",
    category: "mains",
    image: "",
    prepTime: 15,
    cookTime: 25,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "2 tablespoons extra virgin olive oil",
      "1/2 medium onion, thinly sliced",
      "3 garlic cloves, minced",
      "1 tin can diced tomatoes, undrained",
      "1-2 cans cannellini beans, rinsed and drained",
      "3/4 cup artichoke hearts, quartered (in water or brine)",
      "2/3 cup pitted kalamata olives, chopped",
      "2 tablespoons drained capers",
      "1/2 cup chopped fresh basil",
      "--- Garlic Bread ---",
      "1/2 of a standard-size baguette (about 12 inches long)",
      "2 tablespoons extra virgin olive oil",
      "2 cloves garlic, sliced",
      "1 tablespoon dried oregano",
      "2 teaspoons red pepper flakes",
      "Salt",
    ],
    instructions: [
      "Make the puttanesca: Add the olive oil to a large skillet over medium heat. Add the onion and saute, stirring frequently, until just beginning to soften. Add the garlic and stir.",
      "Add the diced tomatoes and bring to a simmer.",
      "Add the cannellini beans and cook for 5 minutes.",
      "Stir in the artichoke hearts, olives, and capers. Simmer for 5 more minutes. Taste for seasoning.",
      "Make the garlic bread: Preheat the oven to 200C. Slice the baguette in half length-wise, and then in half width-wise, to create four 5- or 6-inch sections. Place the baguette pieces on a baking sheet cut-side-up.",
      "In a small skillet or saucepan, heat the remaining two tablespoons of olive oil over medium heat. Add the garlic and stir constantly to ensure that it doesn't burn. Saute until just faintly brown, fragrant, and soft, 1 to 2 minutes. Remove the pan from heat immediately and pour the garlic oil into a small bowl. Poppie adds both the garlic and oil to the bread, not just the oil.",
      "In a small bowl, combine the oregano, red pepper flakes, and salt. Using a pastry brush, brush each slice of baguette evenly with the infused oil. Sprinkle liberally with the oregano-pepper mixture. Bake for 7 to 10 minutes, or until golden brown.",
      "Serve immediately: Divide the puttanesca among four serving bowls. Garnish each with 2 tablespoons of fresh basil. Serve with garlic bread. Keeps perfectly for the next two days -- in fact, the flavours grow more intense.",
    ],
    contributedBy: "Poppie",
    story:
      "Lovely winter recipe and summer. Serve hot in winter and cold in summer. Completely vegan which is weird for this book. It's an Andie Mitchell recipe and I haven't made many changes.",
    tags: [
      "vegan",
      "puttanesca",
      "white-beans",
      "garlic-bread",
      "cannellini",
      "winter",
      "summer",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-20",
    slug: "lens-puff-pastry-square",
    title: "Len's Puff Pastry Square",
    description:
      "An easy summer dish -- puff pastry baked with tomatoes, olives and feta, then topped with dressed rocket and micro-leaves.",
    category: "starters-snacks",
    image: "",
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "Enough bought puff pastry to cover the bottom and sides of a square dish",
      "15 baby tomatoes, halved",
      "Extra virgin olive oil",
      "Vinegar",
      "Salt and pepper",
      "3 tablespoons of chopped olives",
      "Rocket and micro-leaves (if available)",
      "A handful of feta cheese",
      "Parma ham (optional)",
    ],
    instructions: [
      "Roll out the pastry until it is not too thin. Grease a square dish (preferably a basic tin oven dish) and fold the pastry in so that it comes all the way up the sides. Blind bake so that the bottom crispens up.",
      "Add tomatoes, olives and feta and cook at 180C for about 30 minutes until browned and done.",
      "Mix the rocket, micro-leaves and Parma ham (if using). Add olive oil and vinegar so all is coated in dressing. Toss over the baked pastry square.",
    ],
    contributedBy: "Poppie",
    story:
      "This one is easy and lovely as a summer dish.",
    tags: [
      "pastry",
      "puff-pastry",
      "summer",
      "tomato",
      "feta",
      "easy",
      "len",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
];
