import type { Recipe } from "./types";

export const KOOKBOOK_RECIPES_2: Recipe[] = [
  {
    id: "kb-21",
    slug: "spanish-tortilla",
    title: "Spanish Tortilla",
    description:
      "A proper Spanish tortilla with potatoes slow-cooked in olive oil, chorizo, onions and garlic -- the version Len taught us in Italy.",
    category: "starters-snacks",
    image: "",
    prepTime: 15,
    cookTime: 50,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "4 large eggs",
      "5 large potatoes, sliced quite thickly",
      "2 onions, sliced",
      "Chorizo sausage, sliced",
      "Enough olive oil to cover the pan",
      "3 cloves garlic, sliced",
      "1 tsp salt",
    ],
    instructions: [
      "Slice the onion and add together with the garlic and the chorizo. Sweat it down until it is soft. Take care not to burn the garlic.",
      "Add the potatoes to the pan and add more olive oil.",
      "Over medium heat, allow the potatoes and onions to slowly cook for about 30 minutes until cooked.",
      "While your potatoes and onions are simmering, scramble 4 large eggs and set aside.",
      "Once your onions and potatoes are done, add to the scrambled eggs and add salt. Stir to combine.",
      "In a large frying pan, heat 1 tablespoon of the olive oil. Once hot, add your egg, potato and onion mixture, evenly spreading out throughout the pan. Cook for 8-10 minutes until you are able to run a spatula along the border of the pan and can slightly lift the edge of the tortilla up.",
      "Flip the tortilla by placing a large plate on top of the pan and turn upside down. This isn't as simple as it sounds and it's normally an adrenaline moment of watching the meal collapse to the floor. The cheat is to put the pan under the grill and simply brown the top. Much easier. Or, slide the tortilla back into the pan and cook for another 8-10 minutes. Both sides should be slightly browned.",
    ],
    contributedBy: "Poppie",
    story:
      "The last time I made it for you was the last time I cooked it. It was the day after the flood and we showed you the proper Spanish version — we learnt about it in Italy during the Leonard Cohen trip — where the potatoes are cooked slowly in olive oil until ready. It was also after that Dylan and I came down with gastro which probably explains why I've never made it again. I think that is the right way to cook it, but it leaves you with half a bottle of olive oil that tastes of potato. If you want to go with the proper way, cook slowly in the olive oil and then drain oil and combine with the eggs. But let's go the cheat route. For Spaniards the only thing allowed in the recipe is potatoes, but when I learned it from Len there had to be chorizo, onions and garlic added.",
    tags: [
      "spanish",
      "tortilla",
      "eggs",
      "potatoes",
      "chorizo",
      "brunch",
      "leonard-cohen-trip",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-22",
    slug: "andy-bates-beef-and-yorkshire-pud-sandwich",
    title: "Andy Bates' Beef & Yorkshire Pud Sandwich",
    description:
      "Rare beef piled into a homemade Yorkshire pudding with horseradish cream -- we've eaten this so many times because it just works.",
    category: "mains",
    image: "",
    prepTime: 30,
    cookTime: 95,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "8 thick slices of rare beef (from a rump roast cooked to 55C internal, medium rare)",
      "250g plain flour",
      "4 large eggs",
      "550ml milk",
      "200g rocket, watercress and baby spinach salad",
      "1 stick fresh horseradish, grated, or a good horseradish sauce",
      "Bunch of chives",
      "300ml creme fraiche",
      "1 tbsp French dressing",
      "A bit of mayo",
      "Oil for pudding trays",
      "Salt",
      "Pepper",
    ],
    instructions: [
      "Buy a beef rump roast and cook it for about an hour or until the internal temperature is about 55C (medium rare). Rest and slice into 8 thick slices.",
      "To make the Yorkshire puddings, sift the flour and add a pinch of salt. Whisk the eggs and milk then slowly whisk into the flour to make the batter. Leave the mix to rest overnight in the fridge.",
      "Once rested, whisk the mix and bring to room temp. Heat pudding trays with oil at 220C until smoking, then pour in the batter and cook for 35 minutes until risen and golden brown. Do not open the oven door when they are cooking.",
      "Slice each Yorkshire in half (not all the way!) and open like a bun. In a bowl, gently mix the salad and dressing together, then fill each Yorkshire with salad. Season both slices of the beef and lay on top.",
      "Spoon over horseradish sauce mixed with a bit of mayo for a creamier texture. Blend the grated horseradish, chives and creme fraiche together and spoon a large tablespoon over the beef.",
    ],
    contributedBy: "Poppie",
    story:
      "We've eaten this so many times over the years partly because it's so yummy but also because it just works. Andy doesn't go into detail but it's best if you buy a beef rump roast and cook it for about an hour or until the internal temperature is about 55C (medium rare).",
    tags: [
      "beef",
      "yorkshire-pudding",
      "sandwich",
      "horseradish",
      "andy-bates",
      "british",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-23",
    slug: "snoek-pate-and-citrus-salad",
    title: "Snoek Pate & Citrus Salad",
    description:
      "Oak-smoked snoek pounded into a chilli-spiked pate, served with a bright citrus salad -- born from a lunch under the trees in Franschhoek.",
    category: "starters-snacks",
    image: "",
    prepTime: 25,
    cookTime: 0,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "250g oak-smoked snoek (or any similar smoked white fish)",
      "1 red chilli, halved and deseeded",
      "A big pinch of coarse salt",
      "Half a clove of fresh peeled garlic",
      "1 teaspoon finely grated lemon zest",
      "4 tablespoons soft butter",
      "4 tablespoons creme fraiche",
      "Black pepper",
      "1 tbsp (15ml) finely chopped fresh coriander",
      "--- For the salad ---",
      "1/2 cucumber, sliced",
      "Rocket and watercress",
      "1 orange, peeled and divided into segments",
      "1 grapefruit, peeled and divided into segments",
      "Milled black pepper",
      "2 ripe tomatoes, cut into segments",
      "1 small red onion, sliced finely",
      "Basic vinaigrette",
    ],
    instructions: [
      "Flake the fish into a small bowl and remove all bones. Put the chilli into a small mortar with the salt and garlic; pound to a paste. If you don't have a mortar, finely chop the chilli and garlic and mash into a paste with the salt using the back of a spoon or a knife. Set aside.",
      "Scrape the chilli and garlic paste into the bowl of a food processor fitted with a metal blade. Add the flaked fish and all remaining pate ingredients. Pulse lightly to combine without pulverising the fish.",
      "Tip the mixture into a little bowl and refrigerate for three to four hours.",
      "For the salad, combine the cucumber, rocket, watercress, orange segments, grapefruit segments, tomatoes and red onion. Add vinaigrette dressing and toss.",
      "Serve the pate alongside the citrus salad.",
    ],
    contributedBy: "Poppie",
    story:
      "G had this during our Gordon Bay week. You two stayed back at the flat and we drove to Franschhoek and found a little brasserie for lunch. G ordered the pate and it came with the most delicious citrus salad. It also came with a sweetish chutney but we never felt the need to replicate that part. In fact, I've still got the picture of that dish, under the trees on an early day in December 2008. I know you're going to struggle to find Snoek there, but maybe one day... The salad is good enough to go with any summer meal.",
    tags: [
      "snoek",
      "pate",
      "smoked-fish",
      "citrus",
      "salad",
      "south-african",
      "franschhoek",
      "summer",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-24",
    slug: "mother-in-law-egg",
    title: "Mother-in-Law Egg",
    description:
      "Soft-boiled eggs with runny yolks, crumbed and deep-fried until golden -- an impossible recipe where the rewards are pretty meagre.",
    category: "starters-snacks",
    image: "",
    prepTime: 20,
    cookTime: 10,
    servings: 2,
    difficulty: "Hard",
    ingredients: [
      "1-2 eggs per person",
      "1 additional egg, beaten",
      "1/4 cup flour",
      "1/2 cup Panko breadcrumbs (or similar)",
      "Vegetable oil for deep frying",
      "Spinach (for serving)",
    ],
    instructions: [
      "Make the soft boiled eggs, cooking them for 5 1/2 to 6 minutes (or whichever way you prefer but make sure the white is cooked whilst the yolk remains runny).",
      "Once done, crack the shells a bit and leave to cool in cold water (iced if you like) for around 10 minutes. Cracking them will in theory help with the peeling process later on.",
      "Meanwhile heat your vegetable oil to 180C and get your coatings ready. In one bowl the flour, in the next the beaten egg, and in another the breadcrumbs.",
      "Carefully peel the eggs (as the yolk is still runny they will be more difficult to handle and peel than hard boiled eggs -- peeling under running cold water helps). You can do this step up to 2 days prior to the frying and store in the fridge.",
      "When it's time to fry, dust a peeled egg in the flour, then into the beaten egg (draining excess before the next step), and then gently coat well with the breadcrumbs.",
      "Fry the eggs for 45 seconds or until golden brown (no longer than 2 minutes). Serve on wilted spinach, smashed avo, or anything you like.",
    ],
    contributedBy: "Poppie",
    story:
      "In which we had a cook off with Tammy and Jay and Bella won. Impossible recipe and the rewards are pretty meagre. Not worth doing, but has to be listed.",
    tags: ["eggs", "deep-fried", "soft-boiled", "cook-off", "challenge"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-25",
    slug: "reubens-sandwich-pastrami",
    title: "Reuben's Sandwich (Pastrami)",
    description:
      "Homemade pastrami from cured corned beef, loaded onto rye with sauerkraut, melted cheese and a flamethrower finish.",
    category: "mains",
    image: "",
    prepTime: 1470,
    cookTime: 90,
    servings: 4,
    difficulty: "Hard",
    ingredients: [
      "--- For the pastrami ---",
      "2 kg raw, pickled corned beef",
      "1/2 cup brown sugar",
      "2 tablespoons yellow mustard seeds",
      "2 tablespoons black mustard seeds",
      "1/4 cup black peppercorns",
      "1/4 cup coriander seeds",
      "1/2 cup water",
      "--- For the sandwich ---",
      "2 tablespoons fennel seeds",
      "200g sauerkraut with added fennel seeds, warmed",
      "1 soft rye bread",
      "Emmental, Raclette or some easy melting cheese (not Mozzarella -- it needs to have flavour)",
      "Sliced pickled gherkins",
      "Flamethrower",
    ],
    instructions: [
      "Soak the corned beef in a bowl of water with some of the spices and brown sugar for 24 hours. The sugar and water get rid of the saltiness of the corned beef.",
      "Using a pestle and mortar, add the peppercorns, mustard seeds and coriander and grind until coarsely chopped.",
      "Preheat the oven to 160C.",
      "Mix the pepper and seeds on a large plate. Dry off the meat once soaked and roll it in the spice mixture.",
      "Place onto a trivet, pour in a half cup of water, then cover with foil and cook for 1 1/2 hours. You're looking for a medium internal temperature of about 65-70C. Rare to medium.",
      "If you simply bought pastrami slices, skip the above steps and assemble the sandwich: arrange pastrami, warmed sauerkraut with fennel seeds, sliced gherkins, and cheese on rye bread. Always with the cheese on top.",
      "Burn till nearly burnt with the flamethrower and don't forget that it gets hot.",
    ],
    contributedBy: "Poppie",
    story:
      "Now, this would be much better if you could source an uncooked, cured, pastrami with all its spices and cook it from scratch. The part that I cannot fathom and it's an indication of my limited imagination, but a pastrami is a corned beef. Which is my worst food in the world (apart from haggis). And yet a properly cooked pastrami is moist and the most delicious meat. I recently made it from scratch and followed the USA directions and it was completely overdone. Ignore them.",
    tags: [
      "pastrami",
      "reuben",
      "sandwich",
      "sauerkraut",
      "corned-beef",
      "homemade",
      "flamethrower",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-26",
    slug: "philly-steak",
    title: "Philly Steak",
    description:
      "Seared beef fillet with mushrooms and sherry, piled onto baguette and smothered in melted Emmental.",
    category: "mains",
    image: "",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "1/2 kg beef fillet, sliced (not too thinly) and marinated in olive oil and black pepper",
      "1 tablespoon butter",
      "1 punnet Portobellini mushrooms, sliced (or any kind -- would love to try with porcini)",
      "2 tablespoons dried thyme",
      "4 tablespoons dry sherry",
      "Salt and black pepper",
      "1 baguette, halved and sliced across",
      "1 onion, sliced",
      "3 cloves of garlic",
      "Lots of Emmental cheese",
    ],
    instructions: [
      "Over a very high heat, brown the fillet and then remove. It should not be cooked, but browned.",
      "Add the butter, onions and garlic to a medium pan and cook until soft. Add the sliced mushrooms and cook until the water comes and goes. Add the thyme and sherry and cook until reduced. You don't want it watery.",
      "Put the grill on and brown the baguette sides.",
      "Return the fillet to the pan and cook for a minute. Pile onto the baguette and cover with the Emmental cheese. Place under the grill until browned.",
    ],
    contributedBy: "Poppie",
    story:
      "This has become another regular lunch if you don't want dinner kinda meal. It belongs to the triumvirate of trinchado and beef teriyaki because it involves very different ways to use a beef fillet. I doubt whether you will have this problem. I think I need a little break after all this bread and cheese.",
    tags: [
      "philly",
      "steak",
      "beef-fillet",
      "sandwich",
      "mushrooms",
      "cheese",
      "lunch",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-27",
    slug: "cucumber-soup",
    title: "Cucumber Soup",
    description:
      "A cool, creamy cucumber soup with leeks and chicken noodle soup -- pure 70s nostalgia from Barbara's Friday night kitchen.",
    category: "soups",
    image: "",
    prepTime: 15,
    cookTime: 20,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "10 spring onions, chopped",
      "1 tablespoon butter",
      "2 cloves of garlic",
      "2 cucumbers",
      "2 leeks, sliced",
      "1 packet Knorr Chicken Noodle Soup",
      "400ml whipping cream",
      "A healthy dose of Aromat",
      "Salt and pepper",
    ],
    instructions: [
      "Fry the onions, leeks and garlic together with the butter.",
      "Cook the soup packet (add hot water) and let it cool.",
      "Liquidise the cucumber until it resembles a soup (keep 1/4 of the blended cucumber to add back at the end). And the soup.",
      "Add cream, Aromat, salt and pepper and mix. Add the reserved cucumber to give it a contrast in greens.",
    ],
    contributedBy: "Poppie",
    story:
      "I always associate this with Jo and Dom because they have faithfully carried on with Barbara's recipe. It was her favourite summer Friday night (no meat Catholic) meal. The combination is just so 70s.",
    tags: [
      "cucumber",
      "soup",
      "cold-soup",
      "summer",
      "barbara",
      "friday-night",
      "70s",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-28",
    slug: "morganster-tomato-cappuccino-soup",
    title: "Morganster Tomato Cappuccino Soup",
    description:
      "A ridiculously good roasted tomato soup with a frothy cappuccino-style spoom on top, from a now-dead restaurant in Somerset West.",
    category: "soups",
    image: "",
    prepTime: 20,
    cookTime: 75,
    servings: 4,
    difficulty: "Hard",
    ingredients: [
      "--- For the soup ---",
      "1 onion",
      "1 clove garlic",
      "2 tomatoes",
      "100g sundried tomato puree",
      "1 small tin whole peeled tomatoes",
      "A few sprigs thyme",
      "A few leaves basil",
      "A couple leaves oregano",
      "Salt and pepper",
      "30ml honey",
      "15ml olive oil",
      "--- For the spoom ---",
      "Strained soup mixture",
      "Cream in a 40:60 ratio (cream to soup)",
      "--- Garnish ---",
      "Mozzarella or Halloumi wrapped in Parma ham (Buffalo mozzarella works beautifully)",
      "Basil leaves (deep fried if you dare -- it splatters like hell)",
      "--- Sauce Vierge ---",
      "1/2 onion, finely diced",
      "1 large tomato, finely diced",
      "2 leaves basil, finely chopped",
      "10ml olive oil",
      "Salt and pepper to taste",
    ],
    instructions: [
      "Roast the onions, garlic, tomatoes, herbs, olive oil and honey in the oven at 180C for 1 hour.",
      "Add the roasted ingredients to a pot with the whole peeled tomatoes and bring to the boil. Simmer for 10-15 minutes. Blend all together. Season to taste and if need be, add a bit of sugar or honey.",
      "For the spoom: strain the soup well, add cream in a 40:60 ratio (cream to soup). If you have a spoom gun, use it. Otherwise lightly whip it up with a whisk until it is light and nearly in peaks, then blend it with the soup. It creates a creamier, lighter version.",
      "For the Parma ham wrapped cheese: pan fry in a mixture of butter and oil until golden. Prepare just before serving.",
      "For the Sauce Vierge: mix the onion, tomato, basil and olive oil in a bowl just before serving.",
      "To serve: warm the soup, place the cheese garnish in the bottom of the bowl, add the soup, then spoom and sauce vierge on top. The foam sits on top and creates that cappuccino effect.",
    ],
    contributedBy: "Poppie",
    story:
      "Morganster was a restaurant in Somerset West (since dead) that made this most ridiculously good tomato soup. I actually asked for the recipe and the chef kindly sent it to me. It calls for the use of a spoom gun but I'll explain in the text. You've seen these used on Master Chef. What I tend to do is to lightly whip it up with a whisk until it is light and nearly in peaks and then blend it with the soup. It creates a creamier, lighter version of the same soup. The deep fried basil leaves taste absolutely brilliant but they splatter like hell in hot oil. I've decided that the cost to the floor isn't worth it.",
    tags: [
      "tomato",
      "soup",
      "cappuccino",
      "spoom",
      "morganster",
      "somerset-west",
      "restaurant-recreation",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-29",
    slug: "gazpacho",
    title: "Gazpacho",
    description:
      "A classic tomato-based gazpacho with soaked bread, sherry vinegar and a hint of cumin -- in the family since Len first travelled to Spain.",
    category: "soups",
    image: "",
    prepTime: 40,
    cookTime: 0,
    servings: 6,
    difficulty: "Easy",
    ingredients: [
      "2 slices stale crusty bread, crusts removed and torn into smaller chunks",
      "1 1/2 kg ripe tomatoes, roughly chopped",
      "1 small cucumber, peeled and chopped",
      "1 medium red pepper, cored and roughly chopped",
      "1 clove garlic, peeled and chopped",
      "1/2 Spanish onion, roughly chopped",
      "2 tablespoons sherry vinegar",
      "1/2 cup extra virgin olive oil",
      "Pinch of cumin, to taste",
      "Pinch of dry oregano, to taste",
      "Pinch of cayenne pepper, to taste",
      "Salt and freshly ground black pepper to taste",
      "Optional garnishes: croutons, diced veggies, cream, bacon, hard boiled egg",
    ],
    instructions: [
      "Soak the bread for 30 minutes in a small bowl with enough water to keep it submerged. Remove from water and squeeze out almost all the moisture with your hands.",
      "In a large bowl, add all the ingredients and mix to combine. Using a strong blender, blend the mixture in batches until very smooth.",
      "Pass the mixture through a coarse sieve, pushing with the back of a wooden spoon (this part is a bitch). If desired, blend whatever was caught in the sieve and mix that with the soup for a chunkier version.",
      "Taste and adjust seasoning, then cover and refrigerate for 1 hour until well chilled.",
      "Before serving, adjust seasoning and serve in individual glasses or soup bowls. Garnish with croutons, chopped bacon, herbs, black pepper, veggies and/or cream.",
    ],
    contributedBy: "Poppie",
    story:
      "Naturally that needs to be next. It's been in the family since Len first travelled to Spain and the actual making it got passed on to me for some reason.",
    tags: [
      "gazpacho",
      "cold-soup",
      "spanish",
      "summer",
      "tomato",
      "no-cook",
      "len",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-30",
    slug: "white-almond-gazpacho",
    title: "White Almond Gazpacho",
    description:
      "A subtle, elegant white gazpacho where almonds do the heavy work -- far more refined than its tomato cousin.",
    category: "soups",
    image: "",
    prepTime: 20,
    cookTime: 0,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "2 slices white sandwich bread, crusts trimmed, cut into 1-inch cubes",
      "1 cup water",
      "1 1/2 English cucumbers (about 2 small), peeled",
      "1 cup seedless green grapes, plus more for garnish",
      "1/3 cup extra-virgin olive oil, plus more for drizzling",
      "1/3 cup blanched, slivered almonds",
      "2 cloves garlic, coarsely chopped",
      "2 teaspoons sherry vinegar, plus more as needed",
      "1 teaspoon fine salt",
      "Finely chopped fresh chives, for garnish",
    ],
    instructions: [
      "Place the bread cubes in a small bowl, mix in the water, and set aside to soak for 5 minutes.",
      "Meanwhile, peel the cucumbers. Cut into large chunks and place in a blender. Add the grapes, almonds, olive oil, garlic, sherry vinegar and salt.",
      "When the bread is ready, add it and any remaining soaking liquid to the blender. Blend on high speed until very smooth, scraping down the sides of the blender jar as needed, about 2 minutes total.",
      "Cover and refrigerate in the blender jar if it can fit, or transfer to a bowl or airtight container. Refrigerate until chilled and the flavours meld, about 2 hours.",
      "Serve garnished with extra grapes, a drizzle of olive oil, and chopped chives.",
    ],
    contributedBy: "Poppie",
    story:
      "This is one of Arnie's recipes, but I found a close version by Christine Gallary. It's a revelation because it's so different to the tomato based one. Far more subtle in flavour but equally delicious. The almonds do the heavy work here.",
    tags: [
      "gazpacho",
      "white",
      "almond",
      "cold-soup",
      "spanish",
      "summer",
      "grapes",
      "arnie",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-31",
    slug: "carrot-ginger-soup",
    title: "Carrot Ginger Soup",
    description:
      "A velvety carrot and ginger soup with coconut cream -- born at Rhino Ridge for Gillian's 60th and now a firm winter go-to.",
    category: "soups",
    image: "",
    prepTime: 15,
    cookTime: 40,
    servings: 6,
    difficulty: "Easy",
    ingredients: [
      "20-25 small carrots, peeled and roughly chopped (10-15 large carrots, about 8 cups chopped)",
      "2 tablespoons olive oil",
      "1 large onion, diced",
      "3 cloves of garlic, minced or pressed",
      "3 tablespoons grated fresh ginger",
      "Salt and pepper to taste",
      "4-5 cups vegetable or chicken stock",
      "1 tin coconut cream",
      "Chopped parsley for garnish",
      "Sour cream, Greek yogurt, or a swirl of cream (for serving)",
    ],
    instructions: [
      "Put a large pot over medium heat and add the olive oil. Throw the carrots, onions and garlic into the pot and let them cook a bit, just until the onions start to become a little soft.",
      "Grate the ginger over the pot as the vegetables are heating up and stir that in too. Once the mixture starts to become fragrant (you'll smell that ginger as it heats up), add a few pinches of salt and pepper and pour in enough stock to almost cover the vegetables (should be between 4 and 5 cups).",
      "Let this cook over medium-low heat until you can poke a fork in one of the carrot pieces and it falls apart.",
      "Remove it from the heat and puree while it's hot. Using an immersion blender is the easiest method, as you can leave the soup in the pot. If you'd rather use a regular blender you'll probably have to puree in batches.",
      "Once the soup is pureed and you can't see any more chunks, add the can of coconut cream. Using the immersion blender again, blend the coconut cream into the soup. This helps the texture become very velvety. Add more salt and pepper to taste.",
      "Ladle the soup into bowls and serve with a dollop of sour cream, Greek yogurt or a swirl of cream and a sprinkle of chopped parsley. It freezes very well if you're using the coconut cream.",
    ],
    contributedBy: "Poppie",
    story:
      "Gillian's 60th, lockdown, Rhino Ridge getaway soup. Immediately I tasted it I knew that I had to make it and it has become a firm go-to during winter last year. I'm not wild about carrots but the combination with ginger just brings out the sweetness so well.",
    tags: [
      "carrot",
      "ginger",
      "coconut",
      "soup",
      "winter",
      "rhino-ridge",
      "gillians-60th",
      "lockdown",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-32",
    slug: "greek-lentil-soup",
    title: "Greek Lentil Soup",
    description:
      "A hearty red lentil soup with cumin, oregano and lemon, finished with crumbled feta -- stolen from Suzy Karadsheh and followed to the T.",
    category: "soups",
    image: "",
    prepTime: 10,
    cookTime: 30,
    servings: 6,
    difficulty: "Easy",
    ingredients: [
      "Extra virgin olive oil",
      "1 large onion, chopped",
      "3 garlic cloves, minced",
      "2 carrots, chopped",
      "3 tsp dry oregano",
      "1 1/2 tsp cumin",
      "1 tsp rosemary",
      "1/2 tsp red pepper flakes",
      "2 dry bay leaves",
      "1 cup crushed tomatoes (from a can)",
      "7 cups chicken or vegetable stock",
      "2 cups red lentils, rinsed and drained",
      "Kosher salt",
      "Zest of 1 lemon",
      "Juice of 2 lemons",
      "Fresh parsley for garnish",
      "Crumbled feta cheese to serve",
      "Crusty bread to serve",
    ],
    instructions: [
      "Heat 3 tablespoons extra virgin olive oil. Add onions, carrots and garlic. Cook 3 to 4 minutes, stirring regularly.",
      "Add spices and bay leaves. Cook for a few minutes until fragrant, keep stirring so spices don't burn.",
      "Add crushed tomatoes, broth and lentils. Season with kosher salt. Bring to a boil, then lower heat to simmer for 15 to 20 minutes, until lentils are fully cooked.",
      "Remove from heat. If you have the time, let soup cool a bit before using an immersion blender to puree. Pulse a few times until you reach the creamy consistency you are looking for.",
      "Return soup to heat and stir to warm through. Add lemon zest, lemon juice and fresh parsley.",
      "Transfer soup to serving bowls and top with extra virgin olive oil. Top each bowl with a generous sprinkle of feta cheese. Serve with your favourite crusty bread.",
    ],
    contributedBy: "Poppie",
    story:
      "Over the years, I've become more and more of a lentil fan. And I think red lentils are my favourite. They take a relatively short time to cook and pack loads of flavour. I stole this from Suzy Karadsheh and have pretty much followed it to the T.",
    tags: [
      "greek",
      "lentil",
      "soup",
      "red-lentils",
      "feta",
      "lemon",
      "healthy",
      "winter",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-33",
    slug: "green-pea-and-ham-soup",
    title: "Green Pea and Ham Soup",
    description:
      "A two-part affair: a slow-simmered ham hock broth meets frozen peas, mint and creme fraiche -- from April Bloomfield's A Girl and Her Pig.",
    category: "soups",
    image: "",
    prepTime: 20,
    cookTime: 240,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "--- For the ham broth ---",
      "A good sized smoked ham hock",
      "1 Spanish onion, quartered",
      "3 celery stalks",
      "1 carrot, roughly chopped",
      "1 head of garlic, halved horizontally but not peeled",
      "2 bay leaves",
      "Whole black peppercorns",
      "--- For the soup ---",
      "4 tablespoons butter",
      "1/2 Spanish onion, finely chopped",
      "1 carrot, finely chopped",
      "1/2 cup dry white wine",
      "5 mint leaves (leave some for decoration)",
      "600g packet frozen petits pois (more if you like)",
      "Extra virgin olive oil",
      "Salt and black pepper",
      "1 cup creme fraiche",
    ],
    instructions: [
      "Do the broth first. Combine the ham hock, quartered onion, celery, carrot, garlic, bay leaves and peppercorns in a pot with about 8 cups of water. Bring to a boil, then turn down and cover. Simmer for about 3 to 4 hours.",
      "Carefully remove the hocks and strain the liquid over them. Throw away the vegetables.",
      "When the liquid is cool enough, pull off the meat into small chunks. Keep the ham in the liquid. Can be made a day earlier if you like.",
      "To make the soup, put the butter over a medium heat, toss in the onion, carrot and salt. Heat until soft.",
      "Add the wine, some of the mint, 4 cups of the broth (but not the ham pieces) and the frozen peas. April removes the carrots here and returns them at the end for more texture.",
      "Puree, then add the ham pieces. Cook for another 5 minutes until the flavours come together. Add blobs of creme fraiche, salt if needed and mint leaves.",
    ],
    contributedBy: "Poppie",
    story:
      "You know of my love of April Bloomfield's A Girl and Her Pig and this is one of hers. It does require a little more preparation than most but it could keep you going for a good couple of days. It all depends on whether you are a pea and ham kind of person. There's two parts to this. The first is the ham broth.",
    tags: [
      "pea",
      "ham",
      "soup",
      "ham-hock",
      "april-bloomfield",
      "mint",
      "winter",
      "two-day",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-34",
    slug: "french-onion-soup",
    title: "French Onion Soup",
    description:
      "Deep golden caramelised onions in rich beef stock, topped with toasted bread and bubbly Gruyere -- warm, hearty, and here because of the cheese.",
    category: "soups",
    image: "",
    prepTime: 15,
    cookTime: 60,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "1 tablespoon olive oil",
      "About 5 or 6 medium onions",
      "2 tablespoons light brown sugar",
      "1 1/2 teaspoons Worcestershire sauce",
      "2 cloves garlic, minced",
      "1 tablespoon butter",
      "2 tablespoons all-purpose flour",
      "1 cup wine (sherry, marsala, or port are good choices)",
      "8 cups beef stock (chicken stock can be substituted)",
      "1 small bunch fresh thyme",
      "1 bay leaf",
      "1 tablespoon salt",
      "1/2 teaspoon black pepper",
      "16 slices crusty French bread, toasted",
      "2 cups shredded Gruyere or Emmental cheese",
    ],
    instructions: [
      "Heat the olive oil in a large, heavy-bottomed pot over medium heat. Halve, peel and slice the onions thinly, then add them to the pot and stir (a mandolin would be perfect here).",
      "Add the brown sugar and Worcestershire sauce and continue to cook, stirring every few minutes, until the onions become a deep golden brown. Stir in the garlic, cooking until fragrant.",
      "Add the butter to the pot, sprinkle in the flour, and stir everything together. Pour in the wine and stir, scraping any browned bits from the bottom of the pot with your spoon.",
      "Stir in the stock, add the herbs, and allow the soup to come to a simmer. Season with salt and pepper.",
      "Remove the thyme stems and bay leaf, then ladle the soup into heat-safe bowls or those little Le Creuset pots. Top with toasted bread and cheese. Melt the cheese under the grill until browned and bubbly, and serve.",
    ],
    contributedBy: "Poppie",
    story:
      "You know that the reason that it's here is that it has a cheese topping and is warm and hearty. Maybe a break from the wet stuff now. And a small detour into the closest I get to offal.",
    tags: [
      "french",
      "onion",
      "soup",
      "cheese",
      "gruyere",
      "comfort-food",
      "winter",
      "classic",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-35",
    slug: "spicy-chicken-livers",
    title: "Spicy Chicken Livers",
    description:
      "Fresh chicken livers seared in butter then bathed in chilli sauce, sherry and cream -- ideally a two-hander if someone else cleans the livers.",
    category: "starters-snacks",
    image: "",
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    difficulty: "Medium",
    ingredients: [
      "250g fresh chicken livers, cleaned and trimmed",
      "1/4 cup butter",
      "Juice of half a lemon",
      "3 tablespoons dry or medium-cream sherry",
      "3/4 cup fresh whipping cream",
      "1/2 bottle of chilli sauce (Nando's hot or similar)",
      "Salt",
    ],
    instructions: [
      "Trim the livers of any sinews and season with salt and pepper. Heat the butter in a pan until smoking hot. Add the livers and sear until they get a little colour on them but are not cooked through. Take the livers out of the pan and set aside.",
      "In the same pan, add the chilli sauce, salt and the cream. Add the sherry and let the alcohol burn off and reduce until thick.",
      "Add the livers back and cook through.",
      "Serve immediately with fresh bread to soak up the sauce -- French baguette works best.",
    ],
    contributedBy: "Poppie",
    story:
      "This is, ideally, a two-hander of a meal. I'm much happier making it if G cleans the livers. Even the fresh livers that you get from Woolies still have that slimy membrane that I could do without and normally 2 containers only yield one cleaned version. You're looking for firm pieces of liver. This version is the simplified (and much better) version.",
    tags: [
      "chicken-livers",
      "spicy",
      "nandos",
      "offal",
      "quick",
      "starter",
      "sherry",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-36",
    slug: "chicken-liver-pate",
    title: "Chicken Liver Pate",
    description:
      "Smooth chicken liver pate with brandy and thyme, sealed with a thin coating of butter -- it looks dof without it.",
    category: "starters-snacks",
    image: "",
    prepTime: 15,
    cookTime: 15,
    servings: 6,
    difficulty: "Easy",
    ingredients: [
      "250g chicken livers, cleaned",
      "125g butter (and a bit extra to coat the top if desired)",
      "1 large white onion, chopped",
      "1-2 cloves garlic, crushed",
      "2 bay leaves",
      "A couple of sprigs of thyme",
      "40ml brandy",
      "20ml sweet sherry or marsala",
      "Freshly ground black pepper",
      "Salt",
      "Baguette (for serving)",
    ],
    instructions: [
      "Melt the butter in the pan and saute the onion, thyme and garlic for about 5 minutes until onions turn soft.",
      "Add the chicken livers and bay leaves and cook over moderate heat, stirring, until the chicken livers are just done -- about 4-8 minutes. They should still be slightly pink in the middle.",
      "Season with salt and pepper. Add the brandy just before finishing off and allow this to cook for a couple of minutes. Remove from the heat and let it cool.",
      "Remove the bay leaves and blend in a food processor until it is as smooth as it will go. It takes a few minutes. Season with salt and lots of freshly ground pepper to taste.",
      "Spoon the pate into ramekins or other serving dishes and cool. When cool, melt some butter (microwave is great) and pour over the pate. It looks pretty decorated with a bay leaf. Cool in the fridge until serving.",
      "Serve with baguette.",
    ],
    contributedBy: "Poppie",
    story:
      "I know that you don't like the butter on top, but it looks dof without it. A thin coating should be fine. If you leave it out, it also starts to discolour.",
    tags: [
      "chicken-liver",
      "pate",
      "brandy",
      "offal",
      "starter",
      "make-ahead",
      "french",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
];
