import type { Recipe } from "./types";

export const KOOKBOOK_RECIPES_3: Recipe[] = [
  {
    id: "kb-37",
    slug: "baba-ganoush",
    title: "Baba Ganoush",
    description:
      "Smoky roasted eggplant dip with tahini, cumin and coriander. One of those Mediterranean dips that has a specific time and place when it works.",
    category: "starters-snacks",
    image: "",
    prepTime: 10,
    cookTime: 40,
    servings: 6,
    difficulty: "Easy",
    ingredients: [
      "2 medium eggplants",
      "1/4 cup tahini",
      "1/4 cup lemon juice",
      "2 to 3 garlic cloves, finely minced",
      "1/2 teaspoon ground cumin",
      "1/2 teaspoon ground coriander",
      "1/2 teaspoon fine sea salt",
      "2 tablespoons chopped fresh parsley leaves",
      "1 teaspoon olive oil, optional",
    ],
    instructions: [
      "Leave whole but prick the aubergines and place in an oven pre-heated to 180C for about 30-40 minutes. They should slightly collapse in on themselves.",
      "While the eggplants roast, combine tahini, lemon juice, garlic, cumin, coriander and the salt in a medium bowl. Let the flavours infuse.",
      "Scrape out the flesh and add to the tahini mixture. Mash the roasted eggplant into the tahini mixture with a fork until somewhat smooth with some texture remaining.",
      "Top with a drizzle of olive oil. Serve with flatbread.",
    ],
    contributedBy: "Poppie",
    story:
      "This emerged from a conversation with Gwyn after she had tasted it at some restaurant in Edinburgh. It's an interesting idea but like hummus, tzatziki and all those other Mediterranean dips, it has a specific time and place when it works.",
    tags: ["dip", "eggplant", "middle-eastern", "vegetarian", "starter"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-38",
    slug: "shakshuka",
    title: "Shakshuka",
    description:
      "Eggs poached in a spiced tomato and eggplant sauce with chickpeas, feta and fresh coriander. Come to the fort food.",
    category: "mains",
    image: "",
    prepTime: 20,
    cookTime: 45,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "2 medium or 3 small eggplants",
      "Olive oil to brush",
      "3 garlic cloves, crushed",
      "1/3 cup chopped parsley",
      "1/3 cup chopped coriander",
      "1 tablespoon paprika",
      "3/4 teaspoon cumin",
      "2 red chillies, finely chopped",
      "1 white onion, finely chopped",
      "4 tomatoes, roughly chopped",
      "1 x 400g can of tomatoes in puree",
      "1/2 tin of chickpeas",
      "1 tablespoon brown sugar",
      "2 tablespoons lemon juice",
      "1 tablespoon red wine vinegar",
      "4-6 eggs, depending on how many each person wants",
      "Coriander, extra, roughly chopped",
      "Feta, to serve",
      "Salt and pepper",
      "Spinach, to serve",
    ],
    instructions: [
      "Preheat the oven to 180C. Line a large baking tray with baking paper. Pierce and add the eggplant. Drizzle a little olive oil over them. Bake for 25 minutes.",
      "Meanwhile, combine the garlic, parsley, coriander, paprika, cumin and chilli in a medium bowl.",
      "When the eggplants are done, remove from the oven. Scoop out the flesh and add to the spice mix. Stir to combine.",
      "In a large frypan, add a tablespoon of olive oil and the chopped onion, saute for 3-4 minutes over a low heat. Add the chopped tomatoes, chickpeas and cook a further 5 minutes to soften. Add the canned tomatoes and simmer for 5 minutes.",
      "Add the eggplant spice mixture to the tomatoes in the pan. Stir to combine, and bring to a simmer. Add the brown sugar, lemon juice and red wine vinegar. Stir to combine.",
      "Form small hollows in the mixture using a spoon, and crack an egg into each. Scatter with crumbled feta. Cover with a lid and cook for 5-7 minutes, or until the eggs are cooked to your liking. Check frequently in the last couple of minutes as the eggs cook quickly.",
      "Season with salt and pepper and sprinkle extra fresh coriander on top. Serve with crusty ciabatta bread and lightly wilted/fried spinach.",
    ],
    contributedBy: "Poppie",
    story:
      "I've tried to avoid any regular herding of recipes, but this lot started with roasted brinjal and leads onto the sacred Sunday night (\"I don't want to go back to school\") meal. Len used this meal to experiment and produced some ghastly dishes like brawn and calf's liver. My approach has always been the opposite. It doesn't matter whether or not you're hungry, it is the last moment before the external brutality of Monday morning intrudes. Literally it's Come to the fort food.\n\nIt is symbolised by breakfast on Sunday night and for many years that was the unspoken rule. Eggs, bacon, baked beans with chilli and rosemary, toast etc. Over the years, this rule has become increasingly flexible but still hangs in with eggs as its focus.\n\nWe'd never tried Shakshuka until Arnie introduced it to us a couple of years ago. I learned two rules. One, like braaing, it's a macho meal that the middle east men cook and each has their own recipe. Two, don't fuck with another man's shakshuka. Don't stir it, add more salt -- the only response allowed is to \"how would you like your eggs done.\" Here's mine. Steal from it, ignore it etc.",
    tags: [
      "eggs",
      "sunday-night",
      "middle-eastern",
      "comfort-food",
      "brunch",
      "one-pan",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-39",
    slug: "mexican-eggs",
    title: "Mexican Eggs",
    description:
      "Spiced tomato and bean skillet topped with eggs and melted cheddar. Same challenge as the shakshuka -- getting the eggs cooked perfectly.",
    category: "mains",
    image: "",
    prepTime: 10,
    cookTime: 30,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "4 large serrano chillies, diced",
      "1 small onion, finely diced",
      "1 teaspoon olive oil",
      "1 teaspoon ground cumin",
      "1 red/yellow pepper",
      "1 teaspoon cayenne pepper",
      "1 can diced tomatoes with juice (do not drain)",
      "1 can red beans, rinsed and drained well",
      "4 large eggs",
      "1/2 cup cheddar, shredded",
      "Chopped coriander, if desired",
    ],
    instructions: [
      "Using a large skillet, saute the onions and pepper with the spices. Add the beans, diced tomatoes (with juice), and green chilies and bring to a boil. Turn down to a simmer, cover, and cook for about 15-20 minutes or until the sauce has thickened up a bit.",
      "Using the back of a spoon, make a small indentation or pocket in the tomato mixture and carefully crack an egg into it. Add the rest of the eggs, about an inch apart.",
      "Cook for about 5 minutes until the whites start to turn. In the meantime heat the oven grill.",
      "Sprinkle grated cheese over the top of the egg mixture, then return to oven. Grill for 2-3 minutes or until cheese is melted.",
    ],
    contributedBy: "Poppie",
    story:
      "We haven't done these for a while, but they will have the same challenge as the shakshuka -- getting the eggs cooked perfectly. It can be made in one pan and then decanted into ramekins (as in the picture). It also has elements of the bean puttanesca. Come to think of it, a lot of these recipes are evolutions, mergers and acquisitions from others.",
    tags: ["eggs", "mexican", "sunday-night", "one-pan", "comfort-food"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-40",
    slug: "slordig",
    title: "Slordig",
    description:
      "A Dutch-inspired layered sandwich -- literally translates as 'messy'. Build your own with whatever is in the fridge.",
    category: "starters-snacks",
    image: "",
    prepTime: 10,
    cookTime: 5,
    servings: 2,
    difficulty: "Easy",
    ingredients: [
      "Ham, sliced or, if not available, virtually any other cold meat",
      "Pickles in brine",
      "Oil or butter for fried egg",
      "Mature cheddar, sliced",
      "Egg, fried",
      "Toast or brioche",
      "Sliced tomato",
      "Sliced pickled onion",
      "Preferred condiments (tomato sauce, mayo etc.)",
    ],
    instructions: [
      "Get your base toasted, or lightly browned.",
      "Layer away, trying not to get too much mushy stuff piled on top of each other. So, ham, pickle, mayo, cheese etc.",
      "Once finished with the construction, fry the egg to your liking. I like mine soft, because just before eating I like cutting it open and letting the yolk dribble through the other layers.",
    ],
    contributedBy: "Poppie",
    story:
      "This one should be reasonably fresh in your memory. We made it just before you left and Sam had never had it. The story goes that this is a Dutch recipe and literally translates as 'messy'. I've googled it but I think it was another of my father's fabrications for effect. As he was fond of saying \"never let truth get in the way of a good story\". He used to make it often on a Sunday night just because he was able to use whatever was in the fridge.\n\nI'll specify the non-negotiables but go wild with different combinations. Everyone makes their own and can repeat layers or add other things.",
    tags: [
      "sandwich",
      "sunday-night",
      "comfort-food",
      "build-your-own",
      "dutch",
      "len",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-41",
    slug: "gordon-ramsays-scrambled-eggs",
    title: "Gordon Ramsay's Scrambled Eggs",
    description:
      "Lumpy, moist and never dry. The test Gordon uses to decide whether to employ an apprentice chef.",
    category: "mains",
    image: "",
    prepTime: 2,
    cookTime: 5,
    servings: 2,
    difficulty: "Easy",
    ingredients: [
      "2 eggs per person",
      "2 tablespoons butter",
      "Salt and pepper",
      "NO MILK",
    ],
    instructions: [
      "Over medium heat whisk the eggs together and continue whisking until you can see clumps begin to form.",
      "Remove it from heat. Add the butter and salt and pepper.",
      "Continue to move it on and off the heat so that you don't overcook it. It's done when it's lumpy and moist, but not dry.",
    ],
    contributedBy: "Poppie",
    story:
      "His version of this story is that he would require apprentice chefs to make him scrambled eggs and wouldn't employ them if they didn't do it this way.\n\nIt's a really good base that can take on a host of other flavours. Smoked salmon, ham etc. Add at the same time as the butter.",
    tags: ["eggs", "breakfast", "quick", "gordon-ramsay", "sunday-night"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-42",
    slug: "nigellas-lamb-chops",
    title: "Nigella's Lamb Chops",
    description:
      "Marinated lamb rib chops with garlic, chilli, oregano, lemon and olives. One of Nigella's habitual recipes that we have often.",
    category: "mains",
    image: "",
    prepTime: 70,
    cookTime: 15,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "12 lamb rib chops",
      "1/4 cup olive oil, plus 2 tablespoons for frying",
      "3 cloves garlic, peeled and sliced",
      "1 teaspoon chilli flakes",
      "1 teaspoon dried oregano",
      "1 small lemon, zested and juiced",
      "1 teaspoon salt",
      "15 black olives, pitted and sliced",
      "2 long red chillies, deseeded if you're scared, and finely chopped",
    ],
    instructions: [
      "Find a big zip lock. Add lamb, 1/4 cup of oil and add the garlic, chilli flakes and real chilli, oregano, lemon zest, olives and juice. Sprinkle over the salt and the olives and then turn the rib chops in the marinade so that both sides are coated.",
      "Leave the lamb to marinate for 1 hour at room temperature before cooking.",
      "Heat a large frying pan with the 2 tablespoons of oil, and add the chops scraping off the marinade before you put them in the pan. Fry them for a couple of minutes a side on quite a high heat so that they take on some colour.",
      "Turn the heat back down to medium and pour the marinade into the pan over the coloured chops. Cook for about 5 minutes or until the chops feel slightly firm.",
      "Transfer the lamb to a serving plate, pour over the juices from the pan and sprinkle with the chopped red chilli should you feel like enhancing the dried chilli with the pep of fresh.",
    ],
    contributedBy: "Poppie",
    story:
      "Speaking of celebrities, I've cooked many of Jamie's recipes and apart from his breakfast in one pan (which, in itself is hardly an epicurean breakthrough), there's nothing that is a must-have recipe. Wait, there is one which I'll get to later. Not so with Nigella. She has a couple of habitual ones that we have often. Like this one.",
    tags: ["lamb", "nigella", "chilli", "quick", "marinated"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-43",
    slug: "nigellas-chicken-mango-salad",
    title: "Nigella's Chicken Mango Salad",
    description:
      "A fresh summer salad of chicken, mango, chilli and lime with sesame oil. Decidedly a summer meal.",
    category: "sides-salads",
    image: "",
    prepTime: 15,
    cookTime: 0,
    servings: 2,
    difficulty: "Easy",
    ingredients: [
      "1 mango, cut into approx. 1cm cubes",
      "1 spring onion, finely chopped",
      "1-2 red chillies",
      "Juice of 2 limes, to taste",
      "1 cold cooked chicken breast, cut into chunks",
      "1 little gem lettuce, sliced or shredded",
      "1 large handful fresh coriander, chopped but optional",
      "1 teaspoon vegetable oil",
      "4 drops toasted sesame oil",
    ],
    instructions: [
      "Tumble the mango cubes, and any juice they make, into a bowl and, with your hands, mix in the chopped spring onion and chilli and squeeze over the lime juice -- use as much or as little as you want.",
      "Leave all this to steep while getting the lettuce shredded. Tumble in the chunked chicken and shredded lettuce and most of the fresh coriander and, using your hands, toss to combine. Add the oils and toss again then decant onto a large serving plate.",
    ],
    contributedBy: "Poppie",
    story:
      "Decidedly a summer meal. And I've just realised that she appeals to me because she likes chilli as well.",
    tags: ["salad", "chicken", "mango", "nigella", "summer", "chilli", "quick"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-44",
    slug: "ginos-chicken-with-anchovies-olives-and-chilli",
    title: "Gino's Chicken with Anchovies, Olives and Chilli",
    description:
      "Italian braised chicken in balsamic vinegar with anchovies, olives and rosemary. Good recipe, even if Gino oozes more than presents.",
    category: "mains",
    image: "",
    prepTime: 15,
    cookTime: 50,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "3 tablespoons plain flour",
      "8 chicken pieces (drumsticks and bone-in thighs), about 1.2kg in total",
      "6 tablespoons olive oil",
      "4 anchovy fillets in oil, drained",
      "3 garlic cloves, peeled and crushed",
      "3 sprigs of fresh rosemary",
      "2 bay leaves",
      "1 teaspoon dried chilli flakes",
      "100ml balsamic vinegar -- go for something a little better than that crap bottom of the range",
      "100g pitted green olives, drained",
      "200ml passata (sieved tomatoes)",
      "Salt and freshly ground black pepper",
    ],
    instructions: [
      "Put the flour on a large plate and season with salt and pepper. Dust the chicken with the seasoned flour. Heat the oil in a large flameproof casserole over a medium to high heat. When very hot, add half the chicken and fry for about 5 minutes each side or until golden brown all over. Transfer to a large plate using a slotted spoon and set aside. Repeat for the remaining chicken.",
      "Reduce the heat to medium. Add the anchovies, garlic, rosemary and bay leaves and fry for 2 minutes, mashing the anchovies with the back of a spoon until they dissolve, then stir in the chilli flakes.",
      "Increase the heat and pour in the vinegar. Bring to the boil and let it bubble rapidly for 1-2 minutes, stirring and scraping from the bottom of the pan. Stir in the olives and passata. Season with salt.",
      "Return the chicken and its juices to the casserole, pushing the chicken into the sauce to submerge as much as possible. Bring to the boil, then reduce the heat, cover and simmer gently for 30-40 minutes, stirring occasionally, or until the chicken is cooked through and tender.",
    ],
    contributedBy: "Poppie",
    story:
      "I'm not sure if you ever came across any of those interminable cooking shows with smarmy Italian chefs. This one is Gino D'Acampo and yes, he oozes more than presents. Good recipe though.\n\nI've tried it on the stove top and inside the oven at 170C for 1 hour. I prefer the oven. The balsamic needs to draw out its hidden sweetness, so go for something a little better than that crap bottom of the range.",
    tags: [
      "chicken",
      "italian",
      "anchovies",
      "olives",
      "balsamic",
      "gino",
      "one-pot",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-45",
    slug: "ginger-chicken",
    title: "Ginger Chicken",
    description:
      "Sticky, falling-apart chicken in ginger, soy and fish sauce. Cooked in a wok until the stock reduces to a rich glaze.",
    category: "mains",
    image: "",
    prepTime: 130,
    cookTime: 60,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "2 tablespoons sugar",
      "1 tablespoon fish sauce",
      "1 tablespoon oyster sauce",
      "2 tablespoons low sodium soya sauce",
      "Chicken pieces -- legs and thighs",
      "3 tablespoons finely sliced fresh ginger",
      "2 tablespoons vegetable oil",
      "3 tablespoons finely diced garlic",
      "250ml chicken stock",
      "Pinch salt and freshly ground black pepper",
      "4 spring onions, sliced into 4cm lengths",
      "1 long chilli, julienned",
    ],
    instructions: [
      "Combine sugar, fish sauce and oyster sauce in a ziplock bag. Mix well, then add the chicken and ginger, massaging the marinade into the flesh. Try and do this about 2 hours before eating. Turn over the zip lock as you walk past it.",
      "Add oil and garlic and cook until fragrant.",
      "Turn the heat to high then add the chicken, searing all sides.",
      "Pour in the marinade and add the chicken stock. The meal (in a wok) normally takes about 1 hour to cook. You're looking for it to fall apart, just a little, and to get that sticky thickness from the reduced stock and sugar.",
      "Finish with pepper, spring onions and the julienned chilli for those that can handle it.",
      "Serve with fried green beans or asparagus or broccoli. Basmati rice would also help to feed multitudes.",
    ],
    contributedBy: "Poppie",
    story: "",
    tags: ["chicken", "ginger", "asian", "sticky", "wok", "comfort-food"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-46",
    slug: "penelope-casas-veal-with-red-peppers-and-chorizo",
    title: "Penelope Casas' Veal with Red Peppers and Chorizo",
    description:
      "Quick-seared veal cutlets with chorizo, peppers and sherry. From the cookbook that changed the way Len thought about food.",
    category: "mains",
    image: "",
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "1 1/2 pounds veal cutlets, sliced thin",
      "Coarse salt",
      "1 tablespoon olive oil",
      "1 medium onion, chopped",
      "1 clove garlic, minced",
      "1 1/2 red/yellow peppers, finely chopped",
      "1 chorizo sausage (2 ounces), thinly sliced",
      "6 tablespoons dry sherry",
      "6 tablespoons chicken broth",
      "2 tablespoons tomato sauce",
      "1/4 teaspoon thyme",
      "1 bay leaf",
      "Freshly ground pepper",
    ],
    instructions: [
      "Sprinkle the cutlets on both sides with salt. Heat the oil in a large, shallow casserole. Quickly brown the cutlets over high heat and remove them to a warm platter.",
      "Reduce the heat and saute the onion, garlic, and peppers for 5 minutes. Add the chorizo and cook 2 minutes more. Stir in the sherry, chicken broth, tomato sauce, thyme, bay leaf, salt and pepper.",
      "Return the cutlets, spoon some sauce over them. Cover and cook slowly a few minutes. It takes hardly any time to cook as well, so don't let it go too long.",
    ],
    contributedBy: "Poppie",
    story:
      "Len's food bible was Penelope Casas' The Food and Wine of Spain. Published in 1982, it changed the whole way he thought about food. I recall that there were some seriously good recipes there. Dylan might remember that there was a Spanish restaurant on Beyers Naude (where Jack's Paint is now) that made fascinating Spanish food. Colin used to love it. Anyway, I loaned the owner my copy of Penelope's book and the next time we went back for a meal, he had closed down. I never saw the book again. But I remember this.\n\nNot sure if veal is also foie gras for you, Sam.",
    tags: ["veal", "spanish", "chorizo", "sherry", "quick", "len"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-47",
    slug: "jamies-chilli-con-carne",
    title: "Jamie's Chilli Con Carne",
    description:
      "Jamie Oliver's chilli with coffee, cinnamon and molasses sugar. The coffee is what convinced Poppie about this recipe.",
    category: "mains",
    image: "",
    prepTime: 15,
    cookTime: 55,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "1 kg lean beef mince",
      "500ml coffee",
      "3 dried chillies",
      "Olive oil",
      "2 teaspoons ground cumin",
      "1 teaspoon dried oregano",
      "2 fresh bay leaves",
      "2 red onions, peeled and diced",
      "2 fresh chillies",
      "2 cinnamon sticks",
      "10 cloves garlic, peeled and finely sliced",
      "Sea salt",
      "3 tablespoons molasses sugar",
      "Ground black pepper",
      "400g chopped tomatoes (1 tin)",
      "3 orange peppers (or red/yellow), deseeded and sliced",
      "400g beans (tins of kidney, butter or pinto, drained)",
      "Soured cream, to serve",
    ],
    instructions: [
      "Make the coffee and, while it's hot, soak the dried chillies in it for a few minutes to let them rehydrate and absorb the flavour.",
      "Meanwhile, peel and dice the onions and peel and finely slice the garlic.",
      "Add oil in your largest casserole pan on a low heat, add the cumin, oregano, bay leaf and onions. De-seed, slice and add the peppers. Fry for 10 minutes, until the onions have softened. Add the mince and break down until it's browned.",
      "Chop the fresh chillies and add them to the onion mixture along with the cinnamon sticks, sliced garlic, a good pinch of sea salt and black pepper and a splash of the chilli-infused coffee.",
      "Stir, then add the rest of the coffee, the tomatoes, breaking them up with the back of a spoon, and the molasses or sugar. Add the beans.",
      "Leave to simmer with the lid off for about 40 minutes.",
      "Dollop a big spoonful of soured cream over the chilli and serve straight from the pan, with fluffy rice, flatbreads or potatoes and a really nice fresh lemony green salad.",
    ],
    contributedBy: "Poppie",
    story:
      "What convinced me about this recipe is obviously the coffee. He adds paprika, but I've left it out. I don't like that overly chipotle flavour that it adds. He also uses brisket but I've replaced it with mince.",
    tags: [
      "chilli",
      "beef",
      "jamie-oliver",
      "coffee",
      "one-pot",
      "comfort-food",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-48",
    slug: "osso-bucco",
    title: "Osso Bucco",
    description:
      "Granny Gill's legendary slow-braised lamb shin in white wine with a gremolata finish. Do not mess with this recipe.",
    category: "mains",
    image: "",
    prepTime: 20,
    cookTime: 180,
    servings: 6,
    difficulty: "Hard",
    ingredients: [
      "6 lamb shin pieces (Granny Gill's substitute for veal)",
      "Plain flour, seasoned with salt and pepper",
      "3 tablespoons olive oil",
      "1 large onion, finely diced",
      "2 carrots, finely diced",
      "2 sticks celery, finely diced",
      "4 cloves garlic, minced",
      "2 sprigs fresh rosemary",
      "2 bay leaves",
      "1 cup dry white wine -- do not substitute with red wine",
      "400g tin chopped tomatoes",
      "2 cups lamb or chicken stock",
      "2 tablespoons tomato sauce",
      "Salt and pepper",
      "For the gremolata: zest of 1 lemon, 1 clove garlic finely minced, 2 tablespoons finely chopped flat-leaf parsley",
    ],
    instructions: [
      "Season the lamb shin pieces with salt and pepper, then dust in flour. Heat olive oil in a large heavy-based casserole and brown the shanks on all sides. Remove and set aside.",
      "Add the carrots and celery and cook for a while longer. Then add the chopped tomatoes and the stock. It should look overly watery.",
      "Reduce for about an hour until the consistency is right -- juicy rather than watery. Season and add the tomato sauce.",
      "Return the lamb to the casserole. Cover and cook in the oven at 160C for about 2 hours, or until the meat is falling off the bone.",
      "For the gremolata, combine the lemon zest, finely minced garlic and chopped parsley. Scatter over the osso bucco just before serving.",
      "Serve with mash potato or colcannon.",
    ],
    contributedBy: "Granny Gill",
    story:
      "After chasing after a couple of celebrities, it's time to come back home. And here it becomes quite tricky. Because one can either adopt a freewheeling approach -- where anything goes -- or one can become quite proscriptive. I know what I said at the beginning of this. That you can't repeat the recipe ever. But these have become so tried and tested that I don't even bother to look up an original source or take any chances, to see if it's better or worse.\n\nNOTES:\n1. Don't fuck with this recipe. Not only will Gillian get very angry but, as in my case, entirely prohibited me from ever making it again.\n2. G has replaced the veal with the lamb shin. Partly because veal was so difficult to come by at one stage and also partly because lamb gives it a more centred and upfront flavour.\n3. Don't even try and substitute the dry white wine for dry red wine. It has an enormous impact and throws the shape of the dish off completely.\n4. The point above brings me to the weirdest part about making this meal. You know whether or not you've cracked it, purely by the aroma at about the second hour. If it doesn't have that unctuous undertone of rosemary and lamb you've done something wrong.\n5. Don't forget the gremolata. We usually tend to remember after the meal is done, but it does make the final, final note that is needed.\n6. We prefer serving it with mash potato or colcannon rather than rice -- that's entirely up to you.",
    tags: [
      "lamb",
      "slow-cooked",
      "granny-gill",
      "italian",
      "special-occasion",
      "comfort-food",
      "do-not-modify",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-49",
    slug: "poppie-pie",
    title: "Poppie Pie",
    description:
      "A cottage pie with lean mince, topped with parsnip and potato mash -- sometimes with roasted garlic folded through.",
    category: "mains",
    image: "",
    prepTime: 20,
    cookTime: 60,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "500g lean mince",
      "400g chopped tomatoes (1 tin)",
      "1 finely chopped onion",
      "1/2 cup of finely chopped carrots and celery",
      "2 cups of beef stock",
      "1 tablespoon of tomato sauce",
      "3 potatoes",
      "2 parsnips (if available)",
      "2 cloves chopped garlic",
      "Salt and pepper",
      "Butter for mash",
      "Optional: 1 head of garlic for roasting",
    ],
    instructions: [
      "Sweat the onions and garlic off on a medium heat. Once they have softened, add the mince and break down until brown.",
      "Add the carrots and celery and cook for a while longer. Then add the chopped tomatoes and the stock. It should look overly watery.",
      "Reduce for about an hour until the consistency is right -- juicy rather than watery. Season and add the tomato sauce.",
      "In the meantime boil the peeled potatoes and parsnips and mash using lots of butter. If you have the energy, roast a head of garlic -- top cut off, drenched in olive oil and salt and wrapped in tinfoil, 180C for an hour. Add about 4 roasted cloves to the mash.",
      "Assemble and cook at 180C until the mash starts to brown and the mince bubbles.",
    ],
    contributedBy: "Poppie",
    story:
      "It's very difficult to write about this one. Over the years I've tried using a mix of lean beef mince and pork, beef and lamb and pretty much everything in between. What changed it for me and made it permanent, were simple additions that gave it the familiar taste.",
    tags: ["pie", "mince", "comfort-food", "family-favourite", "cottage-pie"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-50",
    slug: "pickled-fish",
    title: "Pickled Fish",
    description:
      "Traditional South African Easter pickled fish with turmeric, curry and vinegar. Better after a couple of days in the fridge.",
    category: "seafood",
    image: "",
    prepTime: 20,
    cookTime: 30,
    servings: 8,
    difficulty: "Medium",
    ingredients: [
      "1.7-2 kg filleted hake/cod",
      "Vegetable oil for shallow frying",
      "Seasoned flour for dusting",
      "700ml white wine vinegar",
      "200ml water",
      "200ml sugar",
      "10ml curry powder",
      "7ml salt",
      "15ml black peppercorns",
      "15ml coriander seeds",
      "1 tablespoon turmeric",
      "2 onions, sliced in rings",
      "4 bay leaves",
      "2 green or red chilies, sliced down the middle and left whole",
      "30ml corn flour",
    ],
    instructions: [
      "With the skin still on, cut the filleted fish into cubes or slices.",
      "Dust in seasoned flour. Heat the oil on medium heat in a large frying pan and shallow fry the fish until cooked through but still succulent.",
      "Drain on kitchen paper and remove the skin. It should come off easily.",
      "Gently fry the onions. Combine the vinegar, water, sugar, turmeric, curry powder, salt, peppercorns and coriander in a large saucepan and bring to the boil.",
      "Add the bay leaves and chilies and simmer for 10-12 minutes. The onion should be soft but still a little crunchy.",
      "Mix together the corn flour and water and stir into the boiling sauce. Stir gently until the sauce thickens slightly.",
      "Layer the fish and onions in a large dish (glass or ceramic), pour over the sauce, cover, let it cool, and refrigerate. Pickled fish can be eaten immediately but the flavour is more intense after a couple of days.",
    ],
    contributedBy: "Poppie",
    story:
      "I grew up with the tradition of pickled fish over Easter and I must admit I've always had a bit of a love/hate relationship with it. I only truly figured out what that was when I made it for Gwyn and Pete one Easter Sunday. As I was making it I realised that I hate the skin on pickled fish and once cooked it's so easy to remove and that makes it a completely different dish.",
    tags: [
      "fish",
      "pickled",
      "easter",
      "south-african",
      "tradition",
      "holiday",
      "make-ahead",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-51",
    slug: "bobotie",
    title: "Bobotie",
    description:
      "Classic South African spiced mince bake with a custard topping of egg, mayo and yoghurt. The first dish Poppie learned to make.",
    category: "mains",
    image: "",
    prepTime: 20,
    cookTime: 50,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "2 thick slices of good white bread, crusts removed",
      "1 tablespoon vegetable oil",
      "2 tablespoons butter",
      "1 large onion, finely chopped",
      "500g lean beef mince",
      "2 cloves garlic, grated or crushed",
      "1 heaped tablespoon curry powder",
      "1 heaped teaspoon masala (if unavailable, double-up the curry powder)",
      "2 teaspoons turmeric",
      "2 teaspoons ground cumin",
      "2 teaspoons ground coriander",
      "2 tablespoons Mrs Ball's chutney",
      "Salt",
      "1 tablespoon apricot jam",
      "4 bay leaves",
      "1 cup milk",
      "2 eggs",
      "Hellmanns or Heinz mayonnaise",
      "Bulgarian (or Greek) yoghurt",
      "2 tablespoons red wine vinegar",
    ],
    instructions: [
      "Preheat oven to 180 degrees Celsius. Soak the bread in the milk for 5 minutes, remove and squeeze out any excess milk.",
      "Fry the onions in the oil and butter until just transparent, set aside. Add mince and while it's turning brown add the masala and curry powder, cumin, turmeric and coriander.",
      "Tear the soaked bread into small pieces and add to the meat mixture, mix well. Add chutney, vinegar and apricot jam to the meat. Once cooked put into an oven proof dish.",
      "Beat eggs. Add equal parts of mayo and yoghurt. Pour mix over the meat.",
      "Cook for about 40 minutes or until the top starts browning.",
    ],
    contributedBy: "Poppie",
    story:
      "I think this was probably the first dish I learned to make, living by myself, in Kommetjie. As I'm sure you've noticed by now, is that I love a dish if it has its own little quirk. Like a little insider joke. Or a distinctive personality trait. This one was the equal amounts of, at that stage, Miracle Whip, and Bulgarian yoghurt for the custard. And then the eggs. Genius overkill.",
    tags: [
      "south-african",
      "mince",
      "curry",
      "comfort-food",
      "bobotie",
      "classic",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-52",
    slug: "coq-au-vin",
    title: "Coq au Vin",
    description:
      "Chicken braised in red wine with bacon, mushrooms and pearl onions, all added late so they sparkle individually rather than becoming mulch.",
    category: "mains",
    image: "",
    prepTime: 80,
    cookTime: 75,
    servings: 4,
    difficulty: "Hard",
    ingredients: [
      "8 chicken drumsticks and thighs",
      "2 cups red wine",
      "1 cup chicken stock",
      "Optional: 1/4 cup brandy",
      "4 strips bacon (or pancetta which is better), cut into 1/2 inch pieces",
      "1 medium onion, quartered then thinly sliced",
      "Optional: 4 medium carrots, cut into 1-inch pieces",
      "4 cloves garlic, minced",
      "1/2 bottle of passata",
      "2 tablespoons fresh thyme leaves",
      "1-2 punnets of portabellini mushrooms, thickly sliced (porcini if you can find them)",
      "10-15 pearl onions, peeled",
      "Maizena slurry",
    ],
    instructions: [
      "Place the chicken thighs and drumsticks in a medium-sized bowl and pour the wine, chicken stock, and (if using) the brandy over the top. Marinade for an hour. Prep the vegetables and set the oven to 170C.",
      "Add the bacon/pancetta to a large pan over medium-high heat. Cook until the bacon is crispy, about 8 minutes, then remove it from the pan with a slotted spoon.",
      "Remove the chicken from the wine marinade (save the wine) and dry the chicken with paper towels. Sear until it is golden on both sides and then remove the chicken. Pour all but 2 tablespoons of the bacon/chicken oil into a heatproof dish and set it aside.",
      "Add the sliced onion, garlic and carrots to the pan and let them cook until the onion is golden brown. Push the vegetables to the side of the pan and add the passata. Pour the reserved wine marinade into the pan.",
      "Nestle the chicken into the pan and sprinkle the thyme over top. Place in oven and cook for an hour. Towards the end of that time fry the mushrooms and the baby onions separately. The onions take a little time to get a brown and to soften slightly.",
      "Just before serving add the bacon, mushrooms and onions to be coated.",
    ],
    contributedBy: "Poppie",
    story:
      "This recipe is another of those that contain, at their heart, the same basic principle. This time it twins with Beef Bourguignon. The idea here is that, for years, I've made the mistake of adding the baby onions, bacon and mushrooms at the beginning and that way you get a mulch. You want those flavours to sparkle individually and give it some crunch.\n\nI find that cooking chicken in the oven requires that you use a large flat pan and stir as little as possible. That's the only way to reduce the possibility of land-mine chicken. When simply cooked in a pot, it becomes an indistinguishable jumble of bones and meat. I prefer using thighs and drumsticks.",
    tags: [
      "chicken",
      "french",
      "wine",
      "slow-cooked",
      "special-occasion",
      "comfort-food",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-53",
    slug: "beef-bourguignon",
    title: "Beef Bourguignon",
    description:
      "Fall-apart beef braised in red wine with bacon, mushrooms and baby onions. The twin of Coq au Vin with the same secret -- add the garnish late.",
    category: "mains",
    image: "",
    prepTime: 20,
    cookTime: 180,
    servings: 6,
    difficulty: "Hard",
    ingredients: [
      "Glug extra-virgin olive oil",
      "As much bacon as you want, roughly chopped",
      "1 1/2 kg chuck steak, short rib or stewing beef, cut into largish chunks",
      "1 large carrot, sliced 1/2-inch thick",
      "1 large white onion, diced",
      "6 cloves garlic, minced",
      "1 pinch coarse salt and freshly ground pepper",
      "2 tablespoons flour",
      "12 small baby onions (optional)",
      "3 cups red wine like Merlot, or a Tempranillo",
      "2-3 cups beef stock (if using 2 cups of wine, use 3 cups beef stock)",
      "1/2 bottle of passata",
      "1 teaspoon fresh thyme, finely chopped",
      "2 tablespoons fresh parsley, finely chopped",
      "2 bay leaves",
      "1-2 punnets of portabellini mushrooms, thickly sliced (porcini if you can find them)",
      "2 tablespoons butter",
    ],
    instructions: [
      "Preheat oven to 170C. Heat the oil in a large dutch oven or heavy based pot. Saute the bacon over medium heat for about 3 minutes, until crisp and browned. Transfer with a slotted spoon to a large dish and set aside.",
      "Sear the beef in batches in the hot oil/bacon fat until browned on all sides. Remove.",
      "In the remaining oil/bacon fat, saute the carrots, minced garlic and diced onions until softened. Return the beef back into the pot; season with 1/2 teaspoon coarse salt and 1/4 teaspoon ground pepper. Sprinkle with flour, toss well and cook for 4-5 minutes.",
      "Add the wine and enough stock so that the meat is barely covered. Then add the passata, beef stock and herbs.",
      "Cover, transfer to lower part of the oven and simmer for 2 to 3 hours, or until the meat is fall-apart tender. You may want to carefully remove the meat and drain the sauce, discarding the vegetables (see Lamb Shanks method).",
      "In the last 20 minutes of cooking time, prepare your mushrooms and baby onions. Add all to the mix, obviously including the bacon, and serve with mash or colcannon.",
    ],
    contributedBy: "Poppie",
    story:
      "Keeping in mind the last recipe, the only tricky part is finding the right meat. You want something with some fat, like short rib or chuck -- the same meat that you would use for a pie. It must just fall apart without being dry.",
    tags: [
      "beef",
      "french",
      "wine",
      "slow-cooked",
      "special-occasion",
      "comfort-food",
      "winter",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-54",
    slug: "lamb-shanks",
    title: "Lamb Shanks",
    description:
      "Slow-braised lamb shanks with rosemary and vegetables -- then drain, discard the spent veg, and serve in the pure, thickened sauce.",
    category: "mains",
    image: "",
    prepTime: 15,
    cookTime: 180,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "4 lamb shanks",
      "Olive oil",
      "2 onions, roughly chopped",
      "3 carrots, roughly chopped",
      "3 sticks celery, roughly chopped",
      "4 cloves garlic, minced",
      "2 cups red wine",
      "2 cups lamb or beef stock",
      "1/2 bottle passata",
      "Fresh rosemary, several sprigs",
      "2 bay leaves",
      "Salt and pepper",
      "1 tablespoon flour (if needed to thicken)",
    ],
    instructions: [
      "Brown the lamb shanks in olive oil on all sides in a heavy casserole. Remove and set aside.",
      "Add the onions, carrots, celery, garlic and rosemary. Saute until softened. Add the wine, stock and passata. Return the shanks to the pot.",
      "Cover and cook low and slow -- oven at 160C for about 3 hours, or until the meat is falling off the bone.",
      "Carefully remove the shanks and set aside. Drain and sieve the rest of the pot. Discard the vegetables -- they have already donated all their flavour.",
      "Place the shanks back in the sauce. Thicken with a bit of flour if it's too thin. Warm through and serve.",
    ],
    contributedBy: "Poppie",
    story:
      "This is not so much a recipe as a method that overlaps with the beef bourguignon. It's a bit like the getting rid of that tasteless murk of vegetables that have already donated all their flavour. Irrespective of what you use to cook the shanks, add lots of vegetables -- onions, carrots, celery etc. -- and rosemary to the recipe. Once cooked carefully remove the shanks and set aside. Drain and sieve the rest of the pot. Discard the vegetables and place the shanks or the beef back in the sauce. Thicken with a bit of flour if it's too thin. Warm through and serve.",
    tags: ["lamb", "slow-cooked", "winter", "comfort-food", "method"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-55",
    slug: "100-pieces-of-garlic-chicken",
    title: "100 Pieces of Garlic Chicken",
    description:
      "Two whole chickens stuffed and surrounded by 100 cloves of garlic, roasted until fall-apart tender. An event recipe that needs a Friday or Saturday for the garlic hangover.",
    category: "mains",
    image: "",
    prepTime: 20,
    cookTime: 120,
    servings: 8,
    difficulty: "Medium",
    ingredients: [
      "10 heads of garlic -- you are aiming for 100 cloves",
      "2 chickens",
      "2 lemons",
      "Salt and pepper",
      "2 glasses (250ml) of dry white wine",
      "2 handfuls of fresh rosemary",
      "French loaf for the garlic",
    ],
    instructions: [
      "Peel 40 cloves of garlic. These go into the cavity of the chicken together with quarters of lemon and half of the rosemary.",
      "Pre-heat the oven to 165C.",
      "Place the two stuffed chickens into a baking tray. Dress with olive oil, pepper and salt. Pour 1 glass of wine around the birds.",
      "Cook for 45 minutes and then add the unpeeled remainder of the garlic cloves. Add more wine if required. If the chickens look as if they are burning, cover with tinfoil. Cook for another hour and 15 minutes. The chickens need to be at the fall-apart-on-the-bone stage.",
      "Accompany with a simple green leaf salad. It should be largely eaten with your hands. Small squeezed out garlic on the bread, bit of chicken. And some pan juices which will be the garlic and chicken residue.",
    ],
    contributedBy: "Poppie",
    story:
      "This was another recipe that was too decadent not to try. I first came across the recipe in Floyd on France. He called for 1 kg of garlic. It really is an event recipe and needs to be shared preferably on a Friday evening or Saturday so that you can overcome the garlic hangover.",
    tags: [
      "chicken",
      "garlic",
      "roast",
      "special-occasion",
      "event-meal",
      "french",
      "hands-on",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-56",
    slug: "lamb-shoulder",
    title: "Lamb Shoulder",
    description:
      "Slow-roasted lamb shoulder on a bed of rosemary and fennel with whole garlic heads, served with rosemary potatoes and crusty bread for the juices.",
    category: "mains",
    image: "",
    prepTime: 20,
    cookTime: 240,
    servings: 8,
    difficulty: "Medium",
    ingredients: [
      "4 heads of garlic, separated but unpeeled",
      "3-4 kg shoulder of lamb",
      "2 glasses (500ml) of dry red wine",
      "1-2 cups lamb or chicken stock",
      "Fennel bulbs",
      "3 handfuls of fresh rosemary",
      "4-6 potatoes, peeled and cubed",
      "French loaf for the garlic",
      "Salt and pepper",
      "Tinfoil",
      "Olive oil",
    ],
    instructions: [
      "Make a bed for the shoulder of lamb, using the rosemary and the fennel.",
      "Pre-heat the oven to 160C.",
      "Dress with olive oil, pepper and salt. Pour 1 glass of wine or enough to cover the bottom of the pan. Cover with tinfoil.",
      "Depending on the size of the roast it should take about 3 to 4 hours to cook. After about an hour add the unpeeled garlic cloves. Add more wine if required. This is decidedly not a recipe where you let it go unattended. From hour 2 you have to check continually to see that it has enough liquid. After the wine is gone, move on to adding chicken or lamb stock.",
      "With 2 hours to go, add the cubed potato to a frying pan on moderate heat. De-stalk the rosemary and add. Add a generous supply of olive oil and lots of salt. You want them to brown and get crunchy. If they are ready to go in an hour, simply turn off until the lamb is ready.",
      "The pan will generate oil from the lamb fat and garlic, but it's good fat that leads to good cholesterol. The bread is there for those juices. Repeat method for eating chicken -- eat with your hands.",
    ],
    contributedBy: "Poppie",
    story:
      "Although this dish came much later, the original idea came from the chicken and the belief that the best part of any dish was at the bottom of the pan. The shoulder works best, but you can use a leg. With the shoulder you get multiple places for the meat to cling to the bones. This is also a special occasion meal because it's too hands-on and messy.\n\nThe rosemary potatoes are just a way of having another texture and enforcing the rosemary taste.",
    tags: [
      "lamb",
      "roast",
      "garlic",
      "slow-cooked",
      "special-occasion",
      "hands-on",
      "rosemary",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
];
