import type { Recipe } from "./types";

export const KOOKBOOK_RECIPES_4: Recipe[] = [
  {
    id: "kb-57",
    slug: "mince-bunny-chows",
    title: "Mince Bunny Chows",
    description:
      "Durban-style mince curry served in a hollowed-out bread roll. If it doesn't leave mince on your face, you've failed.",
    category: "mains",
    image: "",
    prepTime: 20,
    cookTime: 60,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "1 kg lean mince",
      "3 cardamom pods (or cardamom powder)",
      "5 curry leaves",
      "1 teaspoon turmeric",
      "2 tablespoons hot curry masala",
      "6 potatoes, peeled and cut into small cubes",
      "3 tablespoons coriander, roughly chopped",
      "3 onions, finely chopped",
      "1/2 cup passata",
      "Equal large shakes of cumin and coriander powder",
      "3 tablespoons fresh garlic and ginger, grated",
      "Salt to taste",
      "250 g peas (optional)",
      "Mrs Ball's chutney",
      "3 tablespoons oil",
      "1 cup beef stock",
      "1 cup Greek yoghurt",
      "1/2 cup fresh cut green or red chillies",
      "6 coney rolls (or large bread rolls)",
    ],
    instructions: [
      "Heat oil in a large pot on medium to high heat. Add onions, cardamom pods, cumin, coriander, turmeric, hot masala and curry leaves and fry until golden.",
      "Add the mince meat, garlic, chillies and ginger and braise for 5 minutes.",
      "Add a cup of stock and passata to the mince and cook on medium heat. Season with salt.",
      "Par boil the potatoes and add to the curry. Add the peas and simmer for 8-10 minutes.",
      "Cook for about an hour. Once the potatoes are completely soft and the dish is still slightly soggy, it's ready.",
      "Cut the top off each coney roll and compress the insides to the sides. Spoon in the mince curry, adding chutney and yoghurt on top. Re-seal with the bread top.",
    ],
    contributedBy: "Poppie",
    story:
      "Remember that the fun part of this is that each portion is served in its own (preferably) coney roll where the top is cut out and the insides compressed to the sides. The point of the meal is that it must be messy. If it doesn't leave you with mince on your face you've failed.",
    tags: [
      "curry",
      "mince",
      "bunny-chow",
      "durban",
      "south-african",
      "messy",
      "comfort-food",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-58",
    slug: "curries",
    title: "Curries",
    description:
      "A general method for beef, lamb or chicken curry built on toasted whole spices. The foundation for any good curry in the Kookbook.",
    category: "mains",
    image: "",
    prepTime: 15,
    cookTime: 90,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "1 kg beef, lamb or chicken, cubed",
      "Yellow and black mustard seeds",
      "Cumin seeds",
      "Coriander seeds",
      "Fennel seeds",
      "Fenugreek seeds",
      "1 cinnamon stick",
      "3 cardamom pods",
      "5 curry leaves",
      "1 teaspoon turmeric",
      "2 tablespoons hot curry masala",
      "3 onions, finely chopped",
      "3 tablespoons fresh garlic and ginger, grated",
      "1/2 cup passata",
      "Equal shakes of cumin and coriander powder",
      "1 cup chicken or beef stock",
      "Salt to taste",
      "Ghee for frying",
    ],
    instructions: [
      "Heat ghee in a large pot over medium heat. Add all the whole seeds -- mustard, cumin, coriander, fennel and fenugreek -- along with the cinnamon stick. Wait until they start popping.",
      "Once the seeds are popping, add the onions, cardamom pods, turmeric, hot masala and curry leaves. Fry until golden.",
      "Add the meat (do not brown beforehand -- you want the curry flavour to embed itself in the meat), garlic and ginger. Braise for 5 minutes.",
      "Add stock and passata. Season with salt and simmer on medium-low heat.",
      "Cook for about 1 to 1.5 hours depending on the meat, adding more stock as needed. The curry should be rich and slightly saucy when done.",
    ],
    contributedBy: "Poppie",
    story:
      "I'm not going to go into too much detail because Dyl will not like this method and so I'm not sure how much you'll use this. Whether it's beef, lamb or chicken (obviously using chicken stock) the recipe generally follows the bunny chow recipe with one important difference at the start. I always begin by heating through (normally in ghee) all the seeds I can find in the cupboard. Once they start popping, then add the rest. I never brown the meat before because you want the curry flavour to embed itself in the meat.",
    tags: ["curry", "spices", "beef", "lamb", "chicken", "south-african"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-59",
    slug: "porchetta",
    title: "Porchetta",
    description:
      "A stuffed and rolled pork loin and belly roast using Gennaro's recipe. A lot of work, but it's a Christmas celebration meal.",
    category: "mains",
    image: "",
    prepTime: 60,
    cookTime: 210,
    servings: 10,
    difficulty: "Hard",
    ingredients: [
      "3 kg jacket of pork (loin and belly boned -- ask your butcher to carve it especially)",
      "Salt and pepper",
      "70 ml dry white wine",
      "Zest of 2 lemons",
      "2 tablespoons extra-virgin olive oil, plus extra for rubbing",
      "1 onion, finely chopped",
      "175 g pork mince",
      "175 g chicken liver, finely chopped",
      "10 sage leaves",
      "2 rosemary sprigs",
      "2 thyme sprigs",
      "350 g bread, soaked in lukewarm water",
      "15 g pine nuts, slightly roasted in a pan",
      "30 g sultanas",
      "6 slices mortadella",
      "4 large carrots, sliced lengthways in half",
    ],
    instructions: [
      "Unroll the jacket of pork and lay it flat on a board. Cut into the loin and fold out so it's all about the same thickness. Sprinkle with salt and pepper and rub well in. Drizzle the dry white wine, sprinkle the lemon zest and massage well in. Roll, wrap in cling film and rest in the fridge for about 30 minutes.",
      "Preheat the oven to 220 degrees C.",
      "Heat the olive oil in a pan, add onion and sweat for a couple of minutes. Add the pork mince and brown all over. Add the chicken liver and brown all over too. Remove from the heat and allow to cool. Squeeze the excess water from the bread and chop finely. Add the bread to the cooled meat together with the herbs, pine nuts and sultanas. Mix well.",
      "Take the jacket of pork, discard the cling film and roll out on a board. Line with three slices of mortadella, add the filling and top with the remaining mortadella slices. Carefully roll up the meat and secure well with kitchen string. Massage all over with oil, salt and pepper and place in a lightly greased roasting dish over the carrots.",
      "Place in the oven for 30 minutes. Cover with aluminium foil, lower the oven temperature to 150 degrees C and continue to roast for three hours.",
      "Remove the foil, turn off the oven and leave to rest in the hot oven until it cools down.",
      "Place on a board and carve into slices. Serve immediately or serve cold later. The porchetta will keep for up to a week in the fridge wrapped in foil.",
    ],
    contributedBy: "Poppie",
    story:
      "The first time we had this was in a little delicatessen in Gaiole in Chianti called Taverna Le Cose Buone. We were there for Juliette's wedding. It was a one-man run place -- there's the owner in the picture -- and he insisted that the two of us had porchetta as he had just made it. And no, that's not what we're eating here. It's a lot of work, but it's a Christmas celebration meal. This is Gennaro's recipe (Jamie Oliver's Italian friend chef).",
    tags: [
      "pork",
      "italian",
      "roast",
      "christmas",
      "celebration",
      "stuffed",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-60",
    slug: "mussels-in-chilli-tomato",
    title: "Mussels in Chilli Tomato",
    description:
      "Mussels steamed in a spicy chilli tomato sauce, served with crusty bread for mopping up every last drop.",
    category: "seafood",
    image: "",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "2 tablespoons olive oil",
      "1 onion, finely chopped",
      "2 garlic cloves, crushed",
      "2 small red chillies, finely chopped",
      "1 tablespoon tomato paste",
      "1 tin whole tomatoes, finely chopped (ideally use Hazan's tomato sauce and the discarded onion)",
      "1 lemon, rind finely grated, juiced",
      "2 teaspoons caster sugar",
      "1/2 cup dry white wine",
      "1.5 kg mussels, beards removed",
      "1/2 cup flat-leaf parsley leaves, roughly chopped",
      "Crusty bread, to serve",
      "Salt and pepper, to season",
    ],
    instructions: [
      "Heat oil in a large, deep saucepan over medium heat. Add onion, garlic and chilli. Cook, stirring, for 5 minutes or until onion is soft. Add tomato paste and cook for 1 minute.",
      "Add tomato, lemon rind, lemon juice, sugar and wine to pan. Stir until well combined. Simmer, uncovered, for 10 minutes or until it has thickened up a bit. Season with salt and pepper.",
      "Add mussels to sauce. Cover and cook, shaking pan occasionally, for 3 to 5 minutes or until mussel shells open. Discard unopened shells.",
      "Ladle sauce and mussels into bowls. Sprinkle with parsley. Serve with crusty bread.",
    ],
    contributedBy: "Poppie",
    story:
      "These are the kind of meals that are eaten more like once in a while. Sometimes we go through fads and then make them again and again until we go off them and then only return to them months or years later. I mean how often would one make eggs in a cloud? But these we have cravings for. Mussels are things that we like one of two ways. The classic white wine and cream and in chilli tomatoes.",
    tags: ["mussels", "seafood", "chilli", "tomato", "quick", "crusty-bread"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-61",
    slug: "mussels-in-white-wine",
    title: "Mussels in White Wine",
    description:
      "Classic mussels steamed in white wine and cream. Trickier than the tomato version because you have to get the cream slightly thick.",
    category: "seafood",
    image: "",
    prepTime: 10,
    cookTime: 25,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "1 kg mussels, cleaned and beards removed",
      "2 shallots, diced (ideally shallots)",
      "2 cloves garlic, finely chopped or minced",
      "3 tablespoons butter",
      "1 cup dry white wine",
      "1 1/2 cups whipping cream (not pouring cream, which doesn't thicken as much)",
      "1/2 cup parsley, chopped",
      "Baguettes by the yard",
      "Salt and pepper",
    ],
    instructions: [
      "Wash the mussels for about 30 seconds under cold, running water. Chuck any open ones. Remove beards.",
      "On medium heat, cook shallot in butter for 5 minutes, until slightly translucent.",
      "Add white wine and cook for 5 minutes, reducing the liquid.",
      "Add cream and cook for 5 minutes, stirring occasionally.",
      "Add mussels into the sauce and cook for around 5 minutes, or until the mussels have opened and the sauce has a certain viscosity.",
      "Ladle sauce and mussels into bowls. Sprinkle with parsley. Serve with baguettes.",
    ],
    contributedBy: "Poppie",
    story:
      "While the tomato version is pretty much idiot proof, the white wine version is trickier because you have to get the cream slightly thick. The El Tico version is still too watery at the bottom.",
    tags: [
      "mussels",
      "seafood",
      "white-wine",
      "cream",
      "french",
      "baguette",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-62",
    slug: "baked-sweet-and-sour-chicken",
    title: "Baked Sweet and Sour Chicken",
    description:
      "A fiddly but delicious baked sweet and sour with a crunchy cornstarch coating. Best done as a two-person job.",
    category: "mains",
    image: "",
    prepTime: 30,
    cookTime: 50,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "600 g chicken breast, cut into chunks",
      "2 eggs",
      "3/4 cup flour",
      "1/4 cup cornstarch",
      "Salt and pepper",
      "At least 1 tin pineapple pieces (keep all the juice, buy additional fresh pineapple juice if needed)",
      "Equal measure of red wine vinegar",
      "200 g white sugar",
      "1 onion, chopped",
      "1 tablespoon tomato sauce",
      "100 ml low sodium soy sauce",
      "4 cloves garlic, roughly chopped",
      "Salt, red pepper flakes, and a sprinkle of ground ginger",
      "Pineapple tidbits in juice, fresh or from the tin",
      "1 yellow and 1 red bell pepper, sliced into small pieces",
      "300 g carrots, sliced",
      "Sunflower or canola oil for frying",
      "Sticky rice, to serve",
    ],
    instructions: [
      "Make the sweet and sour sauce: simmer onions, ginger and pineapple juice together. Let it simmer while you prepare the chicken and dice the vegetables.",
      "Coat the chicken: dredge chicken pieces in eggs, then flour, then spiced cornstarch. It's best if one person does the coating and the other the frying. It's messy.",
      "Heat sunflower or canola oil on the stove to 160 degrees. Fry the coated chicken in small batches until crisp and done. Check doneness by removing a piece and cutting in half.",
      "Keep cooked batches warm in the oven at 70 degrees on a tray lined with paper towel to absorb excess oil.",
      "Assemble in a baking dish -- vegetables on the bottom, browned chicken on top, then pour the sweet and sour sauce over everything. Bake for 50 minutes at 170 degrees.",
      "Serve with sticky rice.",
    ],
    contributedBy: "Poppie",
    story:
      "This version may seem a bit fiddly and that's probably why we don't make it (for two) very often, but it is delicious. We have made it for you before. The different colours are for the different stages: the coating, the sauce and the rest. The classic crunchy sweet and sour pork that we always used to make was very simple and messy as well.",
    tags: [
      "chicken",
      "sweet-and-sour",
      "baked",
      "fiddly",
      "pineapple",
      "comfort-food",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-63",
    slug: "paella",
    title: "Paella",
    description:
      "A thoroughly inauthentic Spanish paella with chicken, chorizo, prawns and mussels. Would get you killed in parts of Spain.",
    category: "mains",
    image: "",
    prepTime: 20,
    cookTime: 40,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "2 cups bomba or calasparra rice (just ask for Spanish rice)",
      "4 cups chicken or seafood stock",
      "1 teaspoon saffron threads, placed in the stock",
      "1/4 cup olive oil",
      "1 onion, diced",
      "2 cloves garlic, minced",
      "1 red bell pepper, diced",
      "1 cup diced tomatoes",
      "1 kg chicken thighs, cut into small pieces",
      "2 chorizo sausages, sliced",
      "1 kg prawns, peeled and deveined",
      "A large bunch of mussels",
      "Salt and pepper, to taste",
      "Lemon wedges, for serving",
    ],
    instructions: [
      "Heat the olive oil in a paella pan or large skillet over medium heat. Add the onion, garlic and bell pepper and cook until softened.",
      "Add the chicken and chorizo and cook until the chicken is browned and the chorizo is crispy.",
      "Add the diced tomatoes and cook for a few minutes until the tomatoes have broken down.",
      "Add the rice and stir to coat in the oil. Cook for a few minutes until the rice is slightly toasted. Pour in the stock and saffron, and bring the mixture to a simmer.",
      "Reduce the heat to low, cover the pan and simmer for 15-20 minutes, or until the rice is cooked and most of the liquid is absorbed. Add the mussels and prawns and season with salt and pepper to taste.",
      "Once the paella is cooked, remove it from the heat and let it sit for a few minutes before serving. Garnish with lemon wedges and serve.",
    ],
    contributedBy: "Poppie",
    story:
      "This recipe would get you killed in various parts of Spain as completely lacking in authenticity. The prawns only enter the picture when you get to the coastal region of Spain. Chorizo is generally frowned on, the most preferred meat is rabbit etc. Paella matters because it has become synonymous with major life events. I even have a calendar entry for Len's death paella when he announced that he was definitely going to die. The picture here is Colin's 80th etc.",
    tags: [
      "paella",
      "spanish",
      "rice",
      "seafood",
      "chicken",
      "chorizo",
      "celebration",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-64",
    slug: "patagonian-calamari-two-ways",
    title: "Patagonian Calamari, Two Ways",
    description:
      "Two ways with the apex of calamari: Suzi's decadent butter and crouton version, and a simpler panko deep-fry with lemon mayo.",
    category: "seafood",
    image: "",
    prepTime: 40,
    cookTime: 20,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "--- Suzi's Version ---",
      "At least 1 kg Patagonian calamari tubes",
      "2 cups store-bought croutons (some left whole, some crushed)",
      "1 cup butter",
      "Juice of half a lemon",
      "2 tablespoons small capers",
      "3/4 cup chopped French parsley",
      "Basil leaves for the top",
      "1/2 cup olive oil for marinating",
      "--- Deep-Fried Version ---",
      "1 kg calamari tubes",
      "1/2 cup flour",
      "2 eggs, beaten",
      "1 cup panko breadcrumbs",
      "1/2 lemon, juice and zest",
      "1 cup mayonnaise (made or bought)",
      "Oil for deep frying",
    ],
    instructions: [
      "SUZI'S VERSION: Prepare the serving platter with a layer of croutons and place in an oven to keep warm. Marinate the calamari in olive oil for about an hour.",
      "Melt the butter in a separate pan and add the chopped French parsley, lemon juice and capers. Keep to one side, warm.",
      "Heat the pan to its highest heat and fry the calamari in batches. You want a bit of browning on them. You will know when they're done by the change in colour from translucent white to a more ceramic white. Remove and place on the serving platter. Repeat until all calamari is cooked.",
      "Pour the butter evenly over the calamari. Cover with crushed croutons and dress with basil leaves. Eat immediately.",
      "DEEP-FRIED VERSION: Set up stations with flour, egg and panko. Coat the calamari and preferably put in the fridge for 30 minutes to get the panko to stick.",
      "Add the lemon juice and zest to the mayo. Optionally add a little finely chopped chilli as well.",
      "Deep fry the calamari at about 160 degrees until golden brown. Drain on paper towel. Serve with stick-thin chips and the lemon mayo.",
    ],
    contributedBy: "Poppie",
    story:
      "There is calamari, then Falklands calamari and at the apex of calamari is Patagonian calamari. It comes in the form of tubes and no other form will do. If you ever find it on the island, it is obligatory to try it at least once. The one recipe is a Suzi special and the other is my simpler version. It's completely decadent but that huge plate was 2 kg and 6 people demolished it.",
    tags: [
      "calamari",
      "seafood",
      "deep-fried",
      "butter",
      "patagonian",
      "falklands",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-65",
    slug: "crispy-pork-belly",
    title: "Crispy Pork Belly",
    description:
      "Slow-roasted pork belly with a crackling top that swells and crisps under the grill. Ask your butcher to score it -- it's a bitch to do yourself.",
    category: "mains",
    image: "",
    prepTime: 15,
    cookTime: 195,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "1 1/2 kg pork belly, with the fat scored in a diamond grid pattern about 1/2 inch across the top",
      "Lots of salt",
      "1/2 teaspoon fresh cracked pepper",
      "2 tablespoons dried thyme",
      "A touch of olive oil",
      "Fennel bulbs",
    ],
    instructions: [
      "Preheat your oven to 160 degrees. Line a rimmed baking sheet with foil and place a wire rack inside.",
      "If you have to, score the pork belly. Season the meat side with about half the salt and pepper. Season the underneath and sides with the thyme and pepper. Place the fennel bulbs underneath -- they will give off a slight liquorice flavour.",
      "Add just a touch of olive oil to the scored fat and then loads of salt. Place the pork belly in the oven for 3 hours.",
      "After 3 hours, remove the belly from the oven. Check for doneness -- there should be loads of fat (good thing) at the bottom of the pan.",
      "Turn on the grill in the oven. Grill the pork belly until it starts to swell and crisps. Keep a close eye on the skin as it will scorch very quickly.",
      "Serve with cold beetroot slaw and fennel.",
    ],
    contributedBy: "Poppie",
    story:
      "I don't recall seeing it in Jersey, so maybe it will be another specialist request. If you do have to order it, ask them to score the top. It's a bitch to do it yourself. You're looking for that diamond pattern that is typical of gammon. The top has to be kept sacred and dry. The undersides of the belly are where you try and add flavour. I've tried everything from Chinese 5 spice to miso paste, but I normally just go for dried thyme, fennel bulbs and pepper.",
    tags: ["pork", "belly", "crackling", "slow-roast", "crispy", "fennel"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-66",
    slug: "skinny-lamb-chops",
    title: "Skinny Lamb Chops",
    description:
      "Paper-thin lamb chops cooked over a damn hot braai until burnt and crackling. The point is the burn.",
    category: "mains",
    image: "",
    prepTime: 65,
    cookTime: 5,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "Skinny lamb chops (ask your butcher to cut them thin)",
      "Olive oil for marinating",
      "A touch of chilli",
      "1 lemon, juiced",
      "Salt",
    ],
    instructions: [
      "Find a butcher who will cut you skinny chops -- this is half the battle.",
      "Marinate the chops in olive oil and a touch of chilli for about an hour before cooking.",
      "Get a damn hot braai going. You need serious heat.",
      "Cook the chops over the hot flames. The oil and lamb fat will generate flames -- this is what you want. You're after the burn and the crackle, not a tender lamb chop.",
      "It will only take a couple of minutes. Squeeze over the juice of a lemon and serve immediately.",
    ],
    contributedBy: "Poppie",
    story:
      "It's imperative that these are eaten on a braai. There's two tricks to this. The one is finding a butcher who would be prepared to cut you skinny tjops and the other is to have a damn hot braai. The idea is that you burn the shit out of them. They need to be marinated in olive oil and a touch of chilli (for about an hour before) and the oil and lamb fat generate flames and essentially you cook it over hot flames. Normally, this would be difficult if you're looking for a tender lamb chop, but you're not. You're after the burn and the crackle.",
    tags: ["lamb", "braai", "south-african", "quick", "grilled", "chops"],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-67",
    slug: "chicken-and-mushroom-pie",
    title: "Chicken and Mushroom Pie",
    description:
      "A rich chicken and mushroom pie with a roux-based sauce and puff pastry. The cheat is using a rotisserie chicken.",
    category: "mains",
    image: "",
    prepTime: 30,
    cookTime: 30,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "2 cups rotisserie chicken, shredded and chilled",
      "Puff pastry",
      "350 ml chicken stock",
      "200 g portabellini mushrooms, sliced",
      "2 cloves garlic, crushed",
      "At least 1 tablespoon dried thyme",
      "A splash of sherry",
      "1/2 onion, finely chopped",
      "3 leeks, chopped",
      "4 tablespoons butter",
      "3 tablespoons olive oil",
      "--- For the sauce ---",
      "3 tablespoons butter",
      "3 tablespoons flour",
      "1 cup milk",
      "1 cup chicken stock",
      "1 cup sour cream",
    ],
    instructions: [
      "Heat the oven to 180 degrees C.",
      "In a pan over medium heat, add olive oil, butter, chopped leeks, chopped onion and crushed garlic. Gently fry to soften.",
      "Add sliced mushrooms and fry until golden. Add sherry and chicken stock and simmer for 10 minutes.",
      "Make the sauce: melt the butter in a pot and whisk in the flour. Cook the roux for a few minutes until foamy. Whisk in the milk and stock a little at a time -- this prevents lumps. Bring to a boil and simmer for a few minutes. Stir until it thickens. Remove from heat and whisk in the sour cream. Add to the onion and mushroom mixture.",
      "Remove all the flesh from the rotisserie chicken and add to the mushrooms and stock.",
      "Remove from the heat and spoon into a large ovenproof dish. Top with a sheet of puff pastry, folding the edges over the dish. (Optionally, layer pastry at the bottom too, blind bake, then cover.)",
      "Bake for 20 minutes, or until the pastry is golden. Serve with mash.",
    ],
    contributedBy: "Poppie",
    story:
      "The cheat here is to use a Woolies already cooked chicken, but any good cooked chicken will work. I must admit, I go the extra step and layer pastry at the bottom, blind bake and then cover it.",
    tags: [
      "chicken",
      "mushroom",
      "pie",
      "puff-pastry",
      "comfort-food",
      "roux",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-68",
    slug: "fig-salad",
    title: "Fig Salad",
    description:
      "Roasted black figs with blue cheese, rocket, and a burnt honey dressing. So good, we often have it by itself with nothing else.",
    category: "sides-salads",
    image: "",
    prepTime: 15,
    cookTime: 30,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "16 whole black figs",
      "1 tablespoon raw honey",
      "Olive oil, for drizzling",
      "2 x 40 g bags wild rocket leaves",
      "20 g bag micro leaves",
      "1 blue cheese, crumbled",
      "3 tablespoons almond or peanut brittle",
      "--- For the Burnt Honey Dressing ---",
      "3 tablespoons raw honey",
      "1 tablespoon apple cider vinegar",
      "4 sprigs thyme",
      "1 teaspoon orange zest",
      "1/4 cup orange juice",
      "3 tablespoons olive oil",
      "100 g peanut brittle, chopped",
    ],
    instructions: [
      "Make the dressing: pour the honey into a saucepan and bring to a gentle simmer. Add the thyme and allow to cook for a few minutes until foaming and the honey begins to caramelise and turn a light brown.",
      "Remove from the stove and add the orange juice, zest, apple cider vinegar and olive oil. Pour into a bowl and allow to cool.",
      "Preheat the oven to 180 degrees C. Place the figs onto a baking tray and, using a sharp knife, make a criss-cross incision at the top of each fig. Gently squeeze the bottom to allow it to open up.",
      "Drizzle the figs with a little olive oil and honey, and season with a pinch of salt. Roast in the oven for about 30 minutes, or until just beginning to caramelise. Remove and set aside to cool.",
      "Place the rocket and micro leaves onto a platter and top with the roasted figs. Crumble over the blue cheese and sprinkle over the crushed almond brittle. Drizzle with the burnt honey dressing just before serving.",
    ],
    contributedBy: "Poppie",
    story:
      "I'm including this here because it's a seasonal salad. The recipe is actually a Checkers one and it's a nice concept. It's a promotional paper with a picture of the salad and a QR code. Scan the code and it opens the recipe in a browser window. I've modified it, but you can look at the original recipe if you prefer. It's so good, we often have it by itself with nothing else.",
    tags: [
      "fig",
      "salad",
      "blue-cheese",
      "honey",
      "rocket",
      "seasonal",
      "summer",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-69",
    slug: "baby-spinach-and-nectarine-salad",
    title: "Baby Spinach and Nectarine Salad",
    description:
      "A summery salad of baby spinach, fresh nectarines and avocado with an orange dressing and peanut brittle crunch.",
    category: "sides-salads",
    image: "",
    prepTime: 10,
    cookTime: 0,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "150 g baby spinach",
      "3 nectarines, sliced",
      "2 avocados, freshly sliced",
      "4 tablespoons extra virgin olive oil",
      "100 g peanut brittle, chopped",
      "--- For the Dressing ---",
      "1 orange, juiced",
      "1/2 teaspoon sugar",
      "Salt and pepper",
    ],
    instructions: [
      "Combine all the ingredients for the dressing and set aside.",
      "Assemble the spinach and nectarines on a plate.",
      "Before serving, add freshly sliced avocado, drizzle over the dressing and sprinkle over the peanut brittle.",
    ],
    contributedBy: "Poppie",
    story:
      "This is almost a variation of the fig salad, but also delicious during summer.",
    tags: [
      "salad",
      "spinach",
      "nectarine",
      "avocado",
      "summer",
      "fresh",
      "quick",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-70",
    slug: "spinach-bacon-and-cottage-cheese-salad",
    title: "Spinach, Bacon and Cottage Cheese Salad",
    description:
      "Granny Gill's go-to salad with crispy bacon, chunky cottage cheese and cashew nuts. Goes exceptionally well with a braai.",
    category: "sides-salads",
    image: "",
    prepTime: 15,
    cookTime: 10,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "4 cups fresh spinach leaves, washed and dried",
      "4 strips of bacon, chopped and fried until crunchy",
      "3/4 cup chunky cottage cheese",
      "1/2 punnet button mushrooms, sliced",
      "5-8 spring onions, chopped",
      "1 tablespoon white wine vinegar",
      "2 tablespoons olive oil",
      "Small packet of salted cashew nuts, roughly crushed",
      "Salt and pepper, to taste",
    ],
    instructions: [
      "Start by frying the bacon in a pan until crispy. Once done, remove from the pan and place on a paper towel to cool.",
      "Combine the cottage cheese, white wine vinegar, olive oil, salt and pepper to make the dressing.",
      "In a large mixing bowl, add the mushrooms, spinach, spring onions and chopped bacon. Drizzle the dressing over the salad and toss to combine.",
      "Serve the salad immediately, garnished with additional bacon, crushed cashew nuts and a sprinkle of black pepper.",
    ],
    contributedBy: "Granny Gill",
    story:
      "G's go-to salad and it goes exceptionally well with a braai.",
    tags: [
      "salad",
      "spinach",
      "bacon",
      "cottage-cheese",
      "braai",
      "quick",
      "granny-gill",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-71",
    slug: "the-ultimate-caprese",
    title: "The Ultimate Caprese",
    description:
      "Your common or garden caprese elevated by using burrata instead of dreary mozzarella. Cut it open and let the insides ooze.",
    category: "sides-salads",
    image: "",
    prepTime: 10,
    cookTime: 0,
    servings: 2,
    difficulty: "Easy",
    ingredients: [
      "2-3 ripe tomatoes",
      "Handful of basil leaves",
      "1 burrata",
      "2 tablespoons basil pesto",
      "2 tablespoons olive oil",
      "Good red wine vinegar",
      "Salt and pepper, to taste",
    ],
    instructions: [
      "Slice the tomatoes and arrange on a plate with the basil leaves.",
      "Dress with olive oil and red wine vinegar.",
      "Cut the burrata into four and allow the insides to ooze out and into the rest of the ingredients.",
      "Drizzle with basil pesto. Season with salt and pepper. Devour.",
    ],
    contributedBy: "Poppie",
    story:
      "I know it contains raw tomato, so maybe this is one that Sam eats by herself. It's your common or garden caprese but what sets it apart is that it uses burrata rather than dreary mozzarella.",
    tags: [
      "caprese",
      "salad",
      "burrata",
      "tomato",
      "basil",
      "italian",
      "simple",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-72",
    slug: "roasted-potato-salad-with-lentils-spelt",
    title: "Roasted Potato Salad with Lentils/Spelt",
    description:
      "Roasted baby potatoes with red lentils and baby spinach, tossed in a herb vinaigrette while still hot so the spinach wilts.",
    category: "sides-salads",
    image: "",
    prepTime: 10,
    cookTime: 50,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "1 kilogram baby potatoes, skin on",
      "1 tablespoon olive oil",
      "1 teaspoon sea salt",
      "300 grams cooked red lentils (or spelt if you can get it)",
      "50 grams fresh baby spinach",
      "--- Herb Vinaigrette ---",
      "60 ml extra virgin olive oil",
      "2 tablespoons white wine vinegar",
      "1 teaspoon Dijon mustard",
      "1/2 teaspoon honey or maple syrup",
      "1/2 teaspoon sea salt",
      "1/2 teaspoon black pepper",
    ],
    instructions: [
      "Preheat the oven to 200 degrees C and line a baking tray with parchment paper. Scrub the potatoes and cut any larger ones so they're all roughly the same size (about the size of a golf ball).",
      "Add the potatoes, olive oil and salt to the prepared tray. Use your hands to mix until the potatoes are well coated. Roast for 40-50 minutes, or until very golden.",
      "Make the dressing: add the olive oil, vinegar, mustard, maple syrup, salt and pepper to a jar or small bowl and mix to fully combine. It should be a light golden colour and not separated.",
      "To assemble the salad, place the spinach and lentils into a large bowl. Top with the potatoes immediately after coming out of the oven.",
      "Pour the dressing over the salad and mix until the potatoes are fully coated with dressing and the spinach is wilted. Serve immediately.",
    ],
    contributedBy: "Granny Gill",
    story:
      "This is another one of Gillian's favourites. I prefer to use spelt if you can get hold of it.",
    tags: [
      "potato",
      "salad",
      "lentils",
      "spelt",
      "warm-salad",
      "vinaigrette",
      "granny-gill",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-73",
    slug: "chimichurri",
    title: "Chimichurri",
    description:
      "A fresh herb sauce that goes with everything. Make a lot and keep it in the fridge -- it stores for up to 15 days.",
    category: "sauces-condiments",
    image: "",
    prepTime: 20,
    cookTime: 0,
    servings: 8,
    difficulty: "Easy",
    ingredients: [
      "1/2 cup extra virgin olive oil",
      "1/2 cup red wine vinegar",
      "Juice of a lime",
      "1/2 yellow pepper",
      "2-3 green (or red) chillies",
      "2 cloves garlic, crushed",
      "1 tomato (optional)",
      "3 shallots or 1/2 onion",
      "1/2 bunch parsley",
      "1/2 bunch coriander",
      "5 tablespoons fresh oregano",
      "2 tablespoons fresh thyme",
      "A pinch of salt",
    ],
    instructions: [
      "This sauce should be prepared at least two hours before serving, or the night before, to let the flavours infuse.",
      "If using tomato, chop it up finely. Wash and dry the herbs, then chop finely.",
      "Finely chop the peppers, garlic, chilli and shallots.",
      "In a bowl, place all the chopped ingredients together with the juice of a lime. Add the olive oil and vinegar in equal parts until you get a not-too-runny sauce.",
      "If you want, you can use a food processor, but only use the pulse function -- about three times. You don't want a blob, you want the textures.",
      "Store in a glass jar in the refrigerator for up to 15 days.",
    ],
    contributedBy: "Poppie",
    story:
      "Yes, I know this should be up with the sauces, but I warned of a kind of non-linear logic to this (read, failing memory). Also I'm trying to get to the fact that there are many things that you can do with a good sirloin. So, we would braai the sirloin and then simply accompany it with rosemary potatoes and chimichurri sauce. I normally make a lot and then keep it in the fridge because it goes well with so many different things. Sirloin is a weird cut because it's one that we prefer as medium-rare rather than rare. I find it too chewy rare and slightly meaty at rare.",
    tags: [
      "sauce",
      "chimichurri",
      "argentinian",
      "herbs",
      "braai",
      "steak",
      "condiment",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-74",
    slug: "van-der-hum-grand-marnier-souffle",
    title: "Van der Hum/Grand Marnier Souffle",
    description:
      "A light, airy dessert souffle spiked with Van der Hum or Grand Marnier. Guebert used to set the extra booze alight and pour it over.",
    category: "desserts",
    image: "",
    prepTime: 20,
    cookTime: 20,
    servings: 6,
    difficulty: "Hard",
    ingredients: [
      "12 large eggs, separated",
      "1 litre milk",
      "100 g flour",
      "300 g sugar",
      "Softened butter for greasing",
      "Caster sugar for dusting",
      "3/4 cup Van der Hum or Grand Marnier",
    ],
    instructions: [
      "Bring the milk to a boil.",
      "Beat the egg yolks and add the sugar. Whisk. Add the flour and continue whisking.",
      "Remove the milk from the heat and cool slightly. Pour over the egg and flour mixture and mix through. Replace on heat until it just about comes to the boil. Remove and cool.",
      "Whisk the egg whites until stiffish. Divide into two. Fold the first half into the egg mixture, then gently fold in the second half, trying to keep as much air in as possible.",
      "Butter the ramekins and dust with caster sugar. Add the mixture to 6 ramekins.",
      "Cook at 250 degrees C for 15-20 minutes. Serve immediately.",
    ],
    contributedBy: "Poppie",
    story:
      "The principle is the same but cooked based on very different places and experiences. The Grand Marnier version came from an Italian restaurant in the El Corro centre, called Tichinos. The chef was French and it was one of Colin's regular places -- Colin called it Tickynose. It was there that I first experimented with Bacon, Avo and Feta pizza and I think I've pretty much stuck in that ballpark ever since. The second version was from the chef at Le Souffle and Guebert made the best duck and cherry pie that I have ever tasted. Guebert used to heat more Van der Hum, set it alight and pour it over the souffles. Loved that part.",
    tags: [
      "souffle",
      "dessert",
      "van-der-hum",
      "grand-marnier",
      "french",
      "elegant",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-75",
    slug: "moist-chocolate-cake",
    title: "Moist Chocolate Cake",
    description:
      "A rich chocolate cake with a hard crust and brownie-like centre that sinks a bit when it comes out of the oven. That's the point.",
    category: "desserts",
    image: "",
    prepTime: 15,
    cookTime: 20,
    servings: 8,
    difficulty: "Medium",
    ingredients: [
      "150 g dark chocolate (70% cocoa), plus extra for decorating",
      "4 eggs",
      "225 g caster sugar",
      "125 g unsalted butter",
      "25 g plain flour",
      "50 ml water",
      "50 g ground almonds",
      "2 drops vanilla essence",
      "Icing sugar to dust",
      "Whipped cream to serve",
    ],
    instructions: [
      "Preheat the oven to 170 degrees C. Grease and line an 18 cm loose-bottomed cake tin.",
      "Whisk the eggs, sugar and vanilla essence until light and fluffy.",
      "Put the chocolate, butter and water in a large bowl and heat over a simmering saucepan. Don't stir until it has melded together.",
      "Using a metal spoon, gently fold the creamed mixture into the chocolate mixture. Stir in the almonds and the flour.",
      "Pour into the tin and bake for 20 minutes. Remove, let it cool a bit, dust with icing sugar and serve with whipped cream.",
    ],
    contributedBy: "Poppie",
    story:
      "This is quite similar to the espresso tart, but a lot more oozy at the centre. The cake will sink a bit when it comes out of the oven and should have a hard crust and chocolate brownie feel inside.",
    tags: [
      "chocolate",
      "cake",
      "dessert",
      "brownie",
      "rich",
      "almonds",
      "baking",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-76",
    slug: "kirsch-and-berries-over-ice-cream",
    title: "Kirsch and Berries over Ice Cream",
    description:
      "A cheat dessert of frozen berries fried in butter with caster sugar and kirsch, reduced to a syrup and poured over vanilla ice cream.",
    category: "desserts",
    image: "",
    prepTime: 5,
    cookTime: 10,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "Frozen berries (blackcurrants, raspberries, etc.)",
      "Butter for frying",
      "5-6 tablespoons caster sugar",
      "About 5 tots of kirsch (Schladerer Kirschwasser is the best -- dry and strong)",
      "Vanilla ice cream, to serve",
    ],
    instructions: [
      "In a pan over medium heat, add butter and fry the frozen berries.",
      "Add the caster sugar and a healthy dose of kirsch (about 5 tots).",
      "Wait for it to reduce to a more syrupy texture.",
      "Serve over vanilla ice cream.",
    ],
    contributedBy: "Poppie",
    story:
      "This is basically a cheat recipe and not so much a recipe as a thing that works. You will need to buy kirsch however (it's a very strong cherry liqueur). Schladerer Kirschwasser is the best -- dry and strong and expensive. Don't use a sweet cherry liqueur.",
    tags: [
      "dessert",
      "ice-cream",
      "kirsch",
      "berries",
      "quick",
      "cheat",
      "boozy",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-77",
    slug: "panna-cotta",
    title: "Panna Cotta",
    description:
      "A silky vanilla panna cotta topped with granadilla pulp. The backstory involves a Covid live-stream paella and a chef's secret ingredient.",
    category: "desserts",
    image: "",
    prepTime: 15,
    cookTime: 10,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "8 g gelatine powder",
      "25 ml water",
      "500 ml whipping cream",
      "60 g caster sugar",
      "1 vanilla pod, split lengthways",
      "Granadilla puree, to serve",
    ],
    instructions: [
      "Add the gelatine to a bowl of cold water and soak for 5 minutes.",
      "Pour the cream into a saucepan on medium heat. Add the sugar and vanilla seeds (scrape the seeds out of the pod using the back of a knife). Stir to combine and bring to a simmer, then remove from the heat.",
      "Slightly warm the gelatine, then add to the cream mixture. Stir until completely dissolved.",
      "Pour into six ramekins and place in the fridge to set for at least a couple of hours.",
      "To serve, turn each ramekin upside-down onto a serving plate. If the panna cotta won't drop out, carefully dip the ramekin in a bowl of warm water to loosen it, or cut around the edges. Cover with granadilla pulp.",
    ],
    contributedBy: "Granny Gill",
    story:
      "I'm sure I told you the back story to this one. David very kindly sent me a gift during Covid-19 of a paella. The ingredients arrived the day before and then we live streamed the cooking process with the chef. A bit like those MasterChef tests where you have to follow the chef, step by step. It wasn't bad as paellas go. But as an extra, they sent the ingredients for a Panna Cotta and G decided to make it. It didn't use double cream but rather a long-life cream (not even made of milk) called Meadowland. Meadowland, we discovered later, is a classic chef's trick -- you know the parts of the recipe that they will never tell you about. It's lighter than cream and not as rich but crucially, it never splits and we use it all the time for making peri peri chicken livers and de-boned peri-peri chicken on chips. Glorious stuff. You're going to have to do it the old fashioned way.",
    tags: [
      "panna-cotta",
      "dessert",
      "italian",
      "vanilla",
      "granadilla",
      "set-dessert",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-78",
    slug: "crunchies",
    title: "Crunchies",
    description:
      "Barbara's classic South African oat bars. The first lockdown batch was superb -- the second became muesli. Double the butter and bicarb.",
    category: "baking-breads",
    image: "",
    prepTime: 15,
    cookTime: 30,
    servings: 24,
    difficulty: "Medium",
    ingredients: [
      "1 cup rolled oats",
      "1 cup desiccated coconut",
      "1 cup flour",
      "1 cup sugar",
      "1/2 teaspoon salt",
      "200 g butter (Poppie recommends doubling this)",
      "2 tablespoons golden syrup",
      "1 teaspoon bicarbonate of soda (Poppie recommends doubling this)",
      "2 tablespoons boiling water",
    ],
    instructions: [
      "Preheat the oven to 180 degrees C. Grease a baking tray.",
      "Mix the oats, coconut, flour, sugar and salt together in a large bowl.",
      "Melt the butter and golden syrup together in a saucepan over low heat.",
      "Dissolve the bicarbonate of soda in the boiling water and add to the butter mixture. It will foam up.",
      "Pour the wet mixture over the dry ingredients and mix well. You are looking for a sticky, slightly wet mix before cooking.",
      "Press into the greased baking tray and bake for about 25-30 minutes until golden.",
      "Leave to cool down in the pan for 10 minutes, then turn out and leave to cool for a further 10-12 minutes. Use a serrated knife to cut into squares or slices.",
    ],
    contributedBy: "Poppie",
    story:
      "This is Barbara's recipe and she pretty much made them once a week. The first time I made them during lockdown they were superb, but the second time (as you'll recall) they became muesli. So, my feeling is that you double the amount of butter and the bicarb and water. Maybe even more, but what you are looking for is a sticky slightly wet mix before cooking. Good luck.",
    tags: [
      "crunchies",
      "south-african",
      "oats",
      "baking",
      "bars",
      "barbara",
      "lockdown",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
  {
    id: "kb-79",
    slug: "all-bran-rusks",
    title: "All Bran Rusks",
    description:
      "Hearty South African rusks loaded with oats, bran flakes, sunflower seeds and pistachios. Baked then dried out low and slow.",
    category: "baking-breads",
    image: "",
    prepTime: 15,
    cookTime: 240,
    servings: 40,
    difficulty: "Easy",
    ingredients: [
      "1 kg self-raising flour",
      "10 ml baking powder",
      "5 ml salt",
      "500 ml brown sugar",
      "500 ml oats",
      "750 ml All Bran flakes",
      "500 ml sunflower seeds (or any seeds you like)",
      "60 ml pistachio nuts",
      "500 g butter",
      "500 ml buttermilk",
      "2 eggs, lightly beaten",
    ],
    instructions: [
      "Preheat the oven to 180 degrees C.",
      "Mix all dry ingredients in a large bowl.",
      "Melt the butter, then stir in the buttermilk and eggs.",
      "Pour the wet mixture over the dry ingredients. Use your hands and mix well.",
      "Press into a large roasting pan. Bake for one hour until golden brown and a skewer comes out clean.",
      "Remove from the oven and break or cut into rusk-sized pieces. Place on a baking sheet in the oven at 90 degrees for 3-4 hours to dry out completely.",
    ],
    contributedBy: "Poppie",
    story: "",
    tags: [
      "rusks",
      "south-african",
      "baking",
      "bran",
      "oats",
      "seeds",
      "breakfast",
      "tea-time",
    ],
    featured: false,
    createdAt: "2026-04-12T00:00:00Z",
  },
];
