import type { Member } from "./types";

export const MEMBERS: Member[] = [
  {
    id: "poppie",
    order: 1,
    name: "Poppie",
    title: "The Original Author",
    bio: "Poppie is the reason this cookbook exists. He wrote the original paper version and lit the spark that turned this family into a house full of cooks. A true chef at heart with a passion for adventurous flavours and bold combinations. Ironically, for a man whose surname is Fish, he's not a fan of the stuff. Eats like a bird — a few perfect bites and he's done — but every one of those bites had better be worth it. Loves a good glass of wine with dinner and will happily spend all day in the kitchen getting one dish exactly right.",
    goodAt: [
      "Adventurous, bold flavour combinations",
      "The dish everyone talks about for weeks",
      "Turning simple ingredients into something special",
      "Teaching the whole family to love food",
    ],
    loves: [
      "Complex, layered flavours",
      "A good glass of wine",
      "Experimenting with new ingredients",
      "Cooking all day for the people he loves",
      "Quality over quantity — always",
    ],
    hates: [
      "Fish — yes, really",
      "Bland, uninspired food",
      "Cutting corners on ingredients",
      "Rushing a meal",
    ],
    favouriteFromBook: "To be added",
    favouriteNotInBook: "Something nobody else has tried yet — he's always hunting for the next great dish",
  },
  {
    id: "granny-gill",
    order: 2,
    name: "Granny Gill",
    title: "The Queen of Sides & Salads",
    bio: "Granny Gill is proof that the sides can steal the show. Her salads aren't an afterthought — they're the thing everyone reaches for first. And her Osso Bucco? Dylan's all-time favourite dish. She has that effortless way of making everything on the table feel complete, turning a simple main into a proper spread. If the sides are perfect, the whole meal is perfect — and Granny Gill's sides are always perfect.",
    goodAt: [
      "Sides and salads that steal the show",
      "Osso Bucco — the family benchmark",
      "Turning a simple meal into a feast",
      "Making sure the table always looks full",
    ],
    loves: [
      "Fresh, vibrant salads",
      "Getting the balance of a meal just right",
      "Classic dishes done properly",
      "A well-set table",
      "Feeding the family on a Sunday",
    ],
    hates: [
      "A meal with no sides",
      "Limp salad from a bag",
      "Skipping the vegetables",
      "Overdressed anything",
    ],
    favouriteFromBook: "To be added",
    favouriteNotInBook: "Her own Osso Bucco — she knows it's the best",
  },
  {
    id: "sam",
    order: 4,
    name: "Sam",
    title: "The Baker & The Conscience",
    bio: "Sam is a baker at heart — bread, pastries, anything with dough, she's in her element. Her lasagne is the one everyone requests and her poached eggs are genuinely flawless. But her real superpower? Making sure there are vegetables or salad with every single meal, even when the recipe doesn't call for it. The kids might groan, but they eat it. She's the reason this family eats balanced meals and not just braai meat seven nights a week.",
    goodAt: [
      "Baking — bread especially",
      "The perfect lasagne",
      "Poached eggs — the best in the family",
      "Sneaking vegetables into every meal",
    ],
    loves: [
      "Fresh-baked bread straight from the oven",
      "A proper lasagne with crispy edges",
      "Making sure every plate has something green on it",
      "Weekend baking sessions",
      "Feeding the family something wholesome",
    ],
    hates: [
      "A meal with no vegetables or salad",
      "Wasted food",
      "Recipes that skip the healthy bits",
      "Soggy pastry",
    ],
    favouriteFromBook: "To be added",
    favouriteNotInBook: "A perfect eggs Benedict with homemade hollandaise",
  },
  {
    id: "dylan",
    order: 3,
    name: "Dylan",
    title: "The Braai Master",
    bio: "Dylan lives to feed people — but only people who actually love food. Nothing worse than cooking your heart out for someone who doesn't care. His spaghetti bolognese, roast chicken, and chicken gravy are family staples, and he's the undisputed king of the braai when it comes to chicken. Has a genuine talent for tasting a dish and knowing exactly what's missing — 'it needs something... add sugar' — and being right every time. Cannot stand raw tomato in any form. Cherry tomatoes are the enemy.",
    goodAt: [
      "Spaghetti bolognese",
      "Roast chicken and chicken gravy",
      "Braai — especially chicken",
      "Tasting and fixing flavours on the fly",
    ],
    loves: [
      "Feeding people who genuinely love food",
      "Getting a flavour balance just right",
      "A perfectly braaied chicken",
      "Bold, well-seasoned food",
      "Cooking for a crowd",
    ],
    hates: [
      "Raw tomato — absolutely not",
      "Cherry tomatoes — the worst",
      "Cooking for people who don't appreciate food",
      "Under-seasoned anything",
    ],
    favouriteFromBook: "To be added",
    favouriteNotInBook: "A proper braai spread with all the trimmings",
  },
  {
    id: "bella",
    order: 5,
    name: "Bella",
    title: "The Young Experimenter",
    bio: "Only 15 and already cooking circles around most adults. Bella's crème brûlée is genuinely the best Dylan has ever tasted — and he's not just saying that because she's his daughter. She's drawn to Asian flavours and loves experimenting with things most teenagers wouldn't touch. Can whip up tzatziki from memory without blinking. She doesn't follow recipes so much as use them as a starting point, which is exactly how the best cooks work.",
    goodAt: [
      "Crème brûlée — the family's best",
      "Asian-inspired dishes and flavours",
      "Experimenting with bold combinations",
      "Making things like tzatziki from memory",
    ],
    loves: [
      "Asian flavours — soy, ginger, sesame, chilli",
      "Experimenting with new recipes",
      "Sweet and savoury combinations",
      "Cooking without a recipe",
      "Impressing the family with something unexpected",
    ],
    hates: [
      "Boring, plain food",
      "Being told she's too young to try something",
      "Recipes with no room to improvise",
      "Overcooked noodles",
    ],
    favouriteFromBook: "To be added",
    favouriteNotInBook: "A really good ramen with all the toppings",
  },
  {
    id: "charlie",
    order: 6,
    name: "Charlie",
    title: "The Flavour Detective",
    bio: "Charlie is only 12 but has a palate that most chefs would envy. She can taste a dish and tell you exactly what's in it — and what's missing. She's perfected Poppie's baked beans, which is no small achievement given that Poppie set the bar. A proudly fussy eater, but not in the usual way — she doesn't avoid food, she just refuses to eat bad food. Takes her own salt and pepper to school because the school food needs help. Will not touch leftovers under any circumstances.",
    goodAt: [
      "Identifying flavours like a pro",
      "Poppie's baked beans — perfected",
      "Seasoning — knows exactly how much",
      "Quality control for the whole family",
    ],
    loves: [
      "Perfectly seasoned food",
      "Fresh meals — never reheated",
      "Poppie's recipes",
      "Being the family's official taste-tester",
      "Salt and pepper — carries her own supply",
    ],
    hates: [
      "Leftovers — absolutely not",
      "Under-seasoned school food",
      "Bland anything",
      "Being served something that was better yesterday",
    ],
    favouriteFromBook: "To be added",
    favouriteNotInBook: "Poppie's baked beans — the ones she perfected herself",
  },
  {
    id: "quaid",
    order: 7,
    name: "Quaid",
    title: "The Little Helper",
    bio: "At 8 years old, Quaid is the youngest in the kitchen but already one of the most enthusiastic. He's a great helper and genuinely loves being involved — stirring, measuring, tasting. Unlike most of the family, he's more of a veg man than a meat eater, which makes him the easiest person to feed a salad to. Has one firm rule at the dinner table: nothing on his plate is allowed to touch. Peas and mash must remain in their own zones at all times.",
    goodAt: [
      "Helping in the kitchen — stirring, measuring, tasting",
      "Eating his vegetables without being asked",
      "Following instructions",
      "Keeping everyone entertained while they cook",
    ],
    loves: [
      "Vegetables — genuinely loves them",
      "Helping in the kitchen",
      "Food that stays in its own zone on the plate",
      "Being part of the action",
      "Simple, well-cooked meals",
    ],
    hates: [
      "Food touching other food on the plate",
      "Too much meat",
      "Mixed-together meals where you can't tell what's what",
      "Being left out of the cooking",
    ],
    favouriteFromBook: "To be added",
    favouriteNotInBook: "A plate of perfectly arranged vegetables — nothing touching",
  },
];
