import type { Recipe } from "./types";

export const RECIPES: Recipe[] = [
  {
    id: "1",
    slug: "dads-famous-fish-and-chips",
    title: "Dad's Famous Fish & Chips",
    description:
      "Crispy beer-battered flathead with golden chips. When your surname is Fish, you'd better know how to cook it properly.",
    category: "seafood",
    image: "/images/recipes/dads-famous-fish-and-chips.jpg",
    prepTime: 30,
    cookTime: 25,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "4 flathead fillets, skin off and pin-boned",
      "1 1/2 cups plain flour",
      "1 cup cornflour",
      "1 teaspoon baking powder",
      "1 teaspoon salt",
      "1 330ml bottle of cold lager",
      "1 egg, lightly beaten",
      "1 kg sebago potatoes, peeled and cut into chips",
      "Vegetable oil for deep frying",
      "Lemon wedges, to serve",
      "Tartare sauce, to serve",
      "Salt and malt vinegar, to serve",
    ],
    instructions: [
      "Peel potatoes and cut into 1cm thick chips. Rinse under cold water and pat dry thoroughly with a clean tea towel.",
      "Heat oil in a deep fryer or large heavy-based saucepan to 160C. Par-cook the chips for 5-6 minutes until soft but not coloured. Remove and drain on paper towel.",
      "Whisk together 1 cup of plain flour, cornflour, baking powder, and salt in a large bowl. Make a well in the centre, pour in the cold beer and egg, and whisk until just combined. A few lumps are fine — don't overwork it.",
      "Pat the fish fillets dry and season with salt. Dust each fillet in the remaining half cup of plain flour, shaking off excess.",
      "Increase oil temperature to 190C. Dip each floured fillet into the batter, let the excess drip off, and carefully lower into the hot oil. Fry for 4-5 minutes until deep golden and cooked through. Drain on a wire rack.",
      "While the fish rests, return the chips to the 190C oil and fry for 2-3 minutes until crispy and golden. Season immediately with salt.",
      "Serve the fish and chips on butcher's paper with lemon wedges, tartare sauce, and plenty of malt vinegar.",
    ],
    contributedBy: "Dad (Fish)",
    story:
      "Dad reckons being born a Fish means he had no choice but to master this dish. Every Friday night growing up, the house smelled like a chippy. He spent years perfecting the batter ratio and insists the secret is ice-cold beer and not overmixing. The kids would line up at the kitchen bench with their plates while he pulled batch after batch out of the fryer. It's become the one dish everyone requests when they visit.",
    tags: [
      "fish",
      "chips",
      "beer-batter",
      "friday-night",
      "classic",
      "deep-fried",
      "family-favourite",
    ],
    featured: true,
    createdAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "2",
    slug: "grandmas-roast-chicken",
    title: "Grandma's Roast Chicken",
    description:
      "A proper Sunday roast with crispy skin, juicy meat, and all the trimmings. The recipe that's anchored every family gathering for decades.",
    category: "mains",
    image: "/images/recipes/grandmas-roast-chicken.jpg",
    prepTime: 20,
    cookTime: 90,
    servings: 6,
    difficulty: "Medium",
    ingredients: [
      "1 whole chicken, about 1.8kg",
      "1 lemon, halved",
      "1 whole garlic bulb, halved crosswise",
      "4 sprigs fresh thyme",
      "4 sprigs fresh rosemary",
      "60g butter, softened",
      "1 tablespoon olive oil",
      "1 teaspoon salt",
      "1/2 teaspoon cracked black pepper",
      "1 kg roasting potatoes, peeled and quartered",
      "3 carrots, peeled and cut into chunks",
      "1 brown onion, cut into wedges",
    ],
    instructions: [
      "Preheat oven to 220C (200C fan-forced). Remove chicken from the fridge 30 minutes before cooking to bring it to room temperature. Pat the chicken dry inside and out with paper towel.",
      "Mix the softened butter with salt, pepper, and the leaves from 2 sprigs each of thyme and rosemary. Gently loosen the skin over the breast and push the herb butter underneath, smoothing it out evenly.",
      "Stuff the cavity with the lemon halves, garlic bulb, and remaining herb sprigs. Tie the legs together with kitchen string and tuck the wing tips under the body. Rub the outside with olive oil and season generously with salt.",
      "Toss the potatoes, carrots, and onion wedges with a splash of olive oil and salt. Scatter them in a large roasting tin and place the chicken on top.",
      "Roast at 220C for 20 minutes to crisp the skin, then reduce temperature to 180C (160C fan-forced) and continue roasting for 60-70 minutes, or until the juices run clear when you pierce the thigh.",
      "Remove the chicken from the oven and rest on a board, loosely tented with foil, for at least 15 minutes. Return the vegetables to the oven to keep warm and crisp up.",
      "Carve the chicken and serve on a big platter with the roast vegetables and pan juices spooned over the top.",
    ],
    contributedBy: "Grandma Coppard",
    story:
      "Grandma Coppard made this roast every single Sunday without fail. She always said the secret was butter under the skin and letting the bird rest properly — two things she insisted most people get wrong. The whole family would pile into her kitchen after church, and by the time the chook came out of the oven the house was full of noise and the smell of roasting herbs. She never once wrote the recipe down; Mum learned it by standing next to her and watching.",
    tags: [
      "roast",
      "chicken",
      "sunday",
      "classic",
      "family-dinner",
      "comfort-food",
      "traditional",
    ],
    featured: true,
    createdAt: "2024-02-10T10:00:00Z",
  },
  {
    id: "3",
    slug: "mums-pumpkin-soup",
    title: "Mum's Pumpkin Soup",
    description:
      "Velvety smooth pumpkin soup with a hint of nutmeg and a swirl of cream. The ultimate winter warmer that never gets old.",
    category: "soups-stews",
    image: "/images/recipes/mums-pumpkin-soup.jpg",
    prepTime: 15,
    cookTime: 35,
    servings: 6,
    difficulty: "Easy",
    ingredients: [
      "1.2 kg butternut pumpkin, peeled, seeded, and cut into chunks",
      "1 large brown onion, diced",
      "2 cloves garlic, minced",
      "1 large potato, peeled and diced",
      "4 cups chicken or vegetable stock",
      "1/2 teaspoon ground nutmeg",
      "1/2 teaspoon ground cumin",
      "2 tablespoons butter",
      "1/2 cup thickened cream, plus extra to serve",
      "Salt and pepper to taste",
      "Crusty bread, to serve",
    ],
    instructions: [
      "Melt butter in a large heavy-based saucepan over medium heat. Add the diced onion and cook for 4-5 minutes until softened and translucent. Add the garlic and cook for another minute until fragrant.",
      "Add the pumpkin chunks and potato to the pot. Stir to coat in the butter and cook for 2-3 minutes.",
      "Pour in the stock and add the nutmeg and cumin. Bring to the boil, then reduce heat and simmer for 25-30 minutes until the pumpkin and potato are completely tender and falling apart.",
      "Remove from heat and blend until silky smooth using a stick blender. Alternatively, blend in batches in a stand blender, being careful with the hot liquid.",
      "Return to low heat and stir through the cream. Season generously with salt and pepper. Add a splash more stock if the soup is too thick for your liking.",
      "Ladle into warm bowls, finish with a swirl of cream, a crack of pepper, and serve with thick slices of crusty bread.",
    ],
    contributedBy: "Mum",
    story:
      "Mum would put this on the stove the moment the weather turned cold. You could smell it from the front door when you got home from school, and there was always a pot big enough for seconds. She says the potato is the trick — it makes the soup creamy without needing loads of cream. On really cold nights she would serve it in mugs so everyone could wrap their hands around it on the couch.",
    tags: [
      "soup",
      "pumpkin",
      "winter",
      "comfort-food",
      "easy",
      "vegetarian",
      "creamy",
    ],
    featured: true,
    createdAt: "2024-03-05T10:00:00Z",
  },
  {
    id: "4",
    slug: "aunty-jos-bruschetta",
    title: "Aunty Jo's Bruschetta",
    description:
      "Fresh tomato, basil, and balsamic bruschetta on crispy garlic-rubbed sourdough. The taste of summer on a plate.",
    category: "starters-snacks",
    image: "/images/recipes/aunty-jos-bruschetta.jpg",
    prepTime: 15,
    cookTime: 5,
    servings: 4,
    difficulty: "Easy",
    ingredients: [
      "1 sourdough baguette, sliced on the diagonal into 12 pieces",
      "6 ripe roma tomatoes, seeded and finely diced",
      "1/2 red onion, finely diced",
      "2 cloves garlic (1 for rubbing, 1 minced for the topping)",
      "1/3 cup fresh basil leaves, thinly sliced",
      "2 tablespoons extra virgin olive oil, plus extra for drizzling",
      "1 tablespoon balsamic vinegar",
      "1 teaspoon flaky sea salt",
      "1/2 teaspoon cracked black pepper",
      "Shaved parmesan, to serve",
    ],
    instructions: [
      "Combine the diced tomatoes, red onion, minced garlic, basil, olive oil, and balsamic vinegar in a bowl. Season with salt and pepper. Toss gently and set aside for at least 10 minutes to let the flavours meld.",
      "Heat a grill pan or barbecue grill to high heat. Drizzle the sourdough slices with a little olive oil on both sides.",
      "Grill the bread for 1-2 minutes each side until you get nice char marks and the bread is crispy on the outside.",
      "While the bread is still hot, rub one side of each slice with the cut side of the remaining garlic clove. The heat will soften the garlic and infuse the bread.",
      "Spoon the tomato mixture generously onto the garlic-rubbed side of each bread slice. Top with a few shavings of parmesan.",
      "Arrange on a platter, drizzle with a little extra olive oil, and serve immediately while the bread is still warm and crispy.",
    ],
    contributedBy: "Aunty Jo",
    story:
      "Aunty Jo picked this up on a trip to Italy and came back insisting everyone had been making bruschetta wrong. The key, she says, is rubbing raw garlic on hot toast and letting the tomato mixture sit before spooning it on. She makes platters of it every summer barbecue and they vanish within minutes.",
    tags: [
      "bruschetta",
      "italian",
      "summer",
      "starter",
      "tomato",
      "quick",
      "barbecue",
    ],
    featured: false,
    createdAt: "2024-04-12T10:00:00Z",
  },
  {
    id: "5",
    slug: "uncle-steves-beer-battered-onion-rings",
    title: "Uncle Steve's Beer-Battered Onion Rings",
    description:
      "Thick-cut onion rings in a light, crunchy beer batter. Steve's go-to side for barbecues and footy finals.",
    category: "sides-salads",
    image: "/images/recipes/uncle-steves-beer-battered-onion-rings.jpg",
    prepTime: 20,
    cookTime: 15,
    servings: 4,
    difficulty: "Medium",
    ingredients: [
      "3 large brown onions, cut into 1cm thick rings",
      "1 cup plain flour",
      "1/2 cup cornflour",
      "1 teaspoon baking powder",
      "1 teaspoon smoked paprika",
      "1/2 teaspoon garlic powder",
      "1/2 teaspoon salt",
      "1 cup ice-cold lager",
      "1 egg, lightly beaten",
      "Vegetable oil for deep frying",
      "Aioli or tomato sauce, for dipping",
    ],
    instructions: [
      "Separate the onion slices into individual rings. Discard the very small inner rings or save them for another use. Pat the rings dry with paper towel.",
      "In a large bowl, whisk together the plain flour, cornflour, baking powder, smoked paprika, garlic powder, and salt.",
      "Pour in the ice-cold beer and beaten egg. Whisk until just combined — the batter should be slightly lumpy. Let it rest for 5 minutes.",
      "Heat oil in a deep fryer or heavy-based saucepan to 180C. Set up a wire rack over a baking tray for draining.",
      "Working in batches of 4-5 rings, dip each onion ring into the batter, letting the excess drip off, and carefully lower into the hot oil. Fry for 2-3 minutes, turning once, until golden and crispy.",
      "Remove with a slotted spoon and drain on the wire rack. Season with salt immediately while they're still hot.",
      "Serve hot in a big pile with aioli or tomato sauce on the side.",
    ],
    contributedBy: "Uncle Steve",
    story:
      "Uncle Steve brings these to every barbecue and grand final day without being asked. He reckons the secret is using the cheapest, coldest beer you can find, because 'fancy beer makes fancy batter and nobody wants that.' He always fries a test ring first and eats it himself as 'quality control.'",
    tags: [
      "onion-rings",
      "beer-batter",
      "deep-fried",
      "barbecue",
      "side",
      "pub-food",
      "snack",
    ],
    featured: false,
    createdAt: "2024-05-20T10:00:00Z",
  },
  {
    id: "6",
    slug: "grandmas-scones",
    title: "Grandma's Scones",
    description:
      "Light, fluffy scones with a golden top. Best served warm with strawberry jam and a generous dollop of cream.",
    category: "baking-breads",
    image: "/images/recipes/grandmas-scones.jpg",
    prepTime: 15,
    cookTime: 15,
    servings: 12,
    difficulty: "Easy",
    ingredients: [
      "3 cups self-raising flour, plus extra for dusting",
      "1 tablespoon caster sugar",
      "Pinch of salt",
      "80g cold butter, cut into small cubes",
      "1 cup milk",
      "1/2 cup thickened cream",
      "1 teaspoon vanilla extract",
      "1 egg, beaten, for glazing",
      "Strawberry jam, to serve",
      "Whipped cream, to serve",
    ],
    instructions: [
      "Preheat oven to 220C (200C fan-forced). Line a baking tray with baking paper and set aside.",
      "Sift the flour, sugar, and salt into a large bowl. Add the cold butter cubes and rub into the flour with your fingertips until the mixture resembles coarse breadcrumbs. Work quickly so the butter stays cold.",
      "Make a well in the centre. Combine the milk, cream, and vanilla, then pour into the well. Use a butter knife to stir in a cutting motion until the dough just comes together. Do not overmix — it should be slightly shaggy.",
      "Turn the dough out onto a lightly floured surface and gently bring it together with your hands. Pat out to about 2.5cm thick. Do not roll with a rolling pin as this knocks out the air.",
      "Use a 6cm round cutter dipped in flour to stamp out rounds. Press straight down and do not twist. Gently re-pat the scraps and cut more rounds.",
      "Place scones close together on the prepared tray so they support each other as they rise. Brush the tops lightly with beaten egg.",
      "Bake for 12-15 minutes until risen and golden on top. They should sound hollow when tapped on the base.",
      "Cool briefly on a wire rack, then serve warm with strawberry jam and a generous spoonful of whipped cream.",
    ],
    contributedBy: "Grandma Coppard",
    story:
      "Grandma could have these on the table in under 30 minutes from the moment someone walked through the door. She made them so often she didn't even measure anymore — just went by feel. The golden rule was never twist the cutter and never use a rolling pin. Anyone who visited left with a full belly and a bag of scones wrapped in a tea towel for the road.",
    tags: [
      "scones",
      "baking",
      "afternoon-tea",
      "classic",
      "jam-and-cream",
      "quick",
      "morning-tea",
    ],
    featured: true,
    createdAt: "2024-06-01T10:00:00Z",
  },
  {
    id: "7",
    slug: "mums-sticky-date-pudding",
    title: "Mum's Sticky Date Pudding",
    description:
      "Rich, moist date pudding drenched in warm butterscotch sauce. The dessert that ends every family dinner on a high note.",
    category: "desserts",
    image: "/images/recipes/mums-sticky-date-pudding.jpg",
    prepTime: 20,
    cookTime: 40,
    servings: 8,
    difficulty: "Medium",
    ingredients: [
      "200g pitted dates, roughly chopped",
      "1 cup boiling water",
      "1 teaspoon bicarbonate of soda",
      "60g butter, softened",
      "3/4 cup brown sugar, firmly packed",
      "2 eggs",
      "1 teaspoon vanilla extract",
      "1 1/2 cups self-raising flour",
      "For the butterscotch sauce:",
      "1 cup brown sugar, firmly packed",
      "300ml thickened cream",
      "80g butter",
      "1 teaspoon vanilla extract",
    ],
    instructions: [
      "Preheat oven to 180C (160C fan-forced). Grease a 20cm square baking dish or 8 individual ramekins.",
      "Place the chopped dates in a bowl, pour over the boiling water, and stir in the bicarbonate of soda. The mixture will foam up. Set aside for 10 minutes to soften.",
      "In a separate bowl, beat the softened butter and brown sugar with electric beaters until pale and creamy. Add the eggs one at a time, beating well after each addition. Stir in the vanilla.",
      "Fold in the flour in two batches, alternating with the date mixture (including all the liquid). Stir until just combined — the batter will be quite wet.",
      "Pour into the prepared dish and bake for 35-40 minutes until a skewer inserted in the centre comes out clean. The top should be firm and springy.",
      "While the pudding bakes, make the butterscotch sauce. Combine the brown sugar, cream, and butter in a small saucepan over medium heat. Stir until the butter melts and the sugar dissolves, then simmer for 5 minutes until slightly thickened. Stir in the vanilla.",
      "Serve the pudding warm, sliced into portions, with the hot butterscotch sauce poured generously over the top. Add a scoop of vanilla ice cream if you're feeling it.",
    ],
    contributedBy: "Mum",
    story:
      "This is the pudding Mum brings out when she really wants to impress. Every birthday, every Christmas, every 'just because' dinner ends with this on the table. Dad is known to sneak back to the kitchen for a second serve when he thinks no one is looking. Mum doubles the sauce recipe now because there was a near-incident one Christmas when it ran out.",
    tags: [
      "dessert",
      "sticky-date",
      "pudding",
      "butterscotch",
      "comfort-food",
      "winter",
      "family-favourite",
    ],
    featured: false,
    createdAt: "2024-07-18T10:00:00Z",
  },
  {
    id: "8",
    slug: "dads-bbq-sauce",
    title: "Dad's BBQ Sauce",
    description:
      "A smoky, tangy barbecue sauce with a bit of heat. Dad's 'secret' recipe that he'll now have to share with the whole family.",
    category: "sauces-condiments",
    image: "/images/recipes/dads-bbq-sauce.jpg",
    prepTime: 10,
    cookTime: 30,
    servings: 10,
    difficulty: "Easy",
    ingredients: [
      "1 cup tomato sauce (ketchup)",
      "1/3 cup apple cider vinegar",
      "1/4 cup brown sugar, firmly packed",
      "2 tablespoons Worcestershire sauce",
      "1 tablespoon Dijon mustard",
      "1 tablespoon smoked paprika",
      "1 teaspoon garlic powder",
      "1 teaspoon onion powder",
      "1/2 teaspoon cayenne pepper",
      "1/2 teaspoon salt",
      "1/4 teaspoon black pepper",
      "1 tablespoon olive oil",
    ],
    instructions: [
      "Heat the olive oil in a medium saucepan over medium heat. Add the garlic powder and onion powder and stir for 30 seconds until fragrant.",
      "Add the tomato sauce, apple cider vinegar, brown sugar, Worcestershire sauce, and Dijon mustard. Stir until well combined.",
      "Add the smoked paprika, cayenne pepper, salt, and black pepper. Stir through and bring the mixture to a gentle simmer.",
      "Reduce heat to low and let the sauce simmer for 25-30 minutes, stirring occasionally, until it thickens and the flavours deepen. It should coat the back of a spoon.",
      "Taste and adjust seasoning. Add more cayenne for heat, more brown sugar for sweetness, or more vinegar for tang.",
      "Remove from heat and let cool. Transfer to a jar or squeeze bottle. The sauce will keep in the fridge for up to 2 weeks.",
    ],
    contributedBy: "Dad (Fish)",
    story:
      "Dad used to guard this recipe like state secrets. If you walked into the kitchen while he was making it, he'd cover the ingredients with a tea towel. The family only got the full recipe after years of negotiations and the agreement that it would stay in The Fish Kitchen. Turns out the secret ingredient was just smoked paprika — but don't tell him we said that.",
    tags: [
      "bbq",
      "sauce",
      "barbecue",
      "smoky",
      "condiment",
      "homemade",
      "grilling",
    ],
    featured: false,
    createdAt: "2024-08-22T10:00:00Z",
  },
  {
    id: "9",
    slug: "grandmas-lemon-cordial",
    title: "Grandma's Lemon Cordial",
    description:
      "Old-fashioned homemade lemon cordial, sweet and tart with real citrus flavour. Nothing from a bottle comes close.",
    category: "drinks",
    image: "/images/recipes/grandmas-lemon-cordial.jpg",
    prepTime: 15,
    cookTime: 10,
    servings: 20,
    difficulty: "Easy",
    ingredients: [
      "6 large lemons",
      "2 cups caster sugar",
      "2 cups water",
      "1 tablespoon citric acid",
      "Zest of 2 lemons",
      "Ice and cold water, to serve",
      "Fresh mint sprigs, to garnish (optional)",
    ],
    instructions: [
      "Juice all 6 lemons and strain the juice through a fine sieve to remove seeds and pulp. You should have about 1 1/2 cups of juice.",
      "Combine the sugar, water, and lemon zest in a medium saucepan over medium heat. Stir until the sugar dissolves completely, then bring to a gentle boil.",
      "Reduce heat and simmer for 5 minutes to create a light syrup. Remove from heat.",
      "Stir in the fresh lemon juice and citric acid while the syrup is still warm. Mix well until the citric acid dissolves.",
      "Let the cordial cool to room temperature, then strain into a sterilised glass bottle or jar. Discard the zest.",
      "To serve, pour about 50ml of cordial into a tall glass, fill with cold water and ice, and stir. Adjust the ratio to taste. The cordial keeps in the fridge for up to 4 weeks.",
    ],
    contributedBy: "Grandma Coppard",
    story:
      "Grandma always had a bottle of this in the fridge. It didn't matter what time of year — if you were thirsty, you got lemon cordial. She used to say she didn't trust the stuff in shops because it was 'more yellow colouring than lemon.' The grandkids would fight over who got the first glass when a fresh batch was made.",
    tags: [
      "cordial",
      "lemon",
      "drink",
      "homemade",
      "summer",
      "refreshing",
      "old-fashioned",
    ],
    featured: false,
    createdAt: "2024-09-10T10:00:00Z",
  },
  {
    id: "10",
    slug: "the-fish-family-christmas-pavlova",
    title: "The Fish Family Christmas Pavlova",
    description:
      "A towering pavlova with a crisp shell and marshmallow centre, piled high with cream and fresh summer fruit. No Fish family Christmas is complete without it.",
    category: "holiday-specials",
    image: "/images/recipes/the-fish-family-christmas-pavlova.jpg",
    prepTime: 30,
    cookTime: 90,
    servings: 10,
    difficulty: "Hard",
    ingredients: [
      "6 egg whites, at room temperature",
      "1 1/2 cups caster sugar",
      "1 tablespoon cornflour",
      "1 teaspoon white vinegar",
      "1 teaspoon vanilla extract",
      "600ml thickened cream",
      "2 tablespoons icing sugar",
      "250g fresh strawberries, hulled and halved",
      "2 kiwi fruit, peeled and sliced",
      "150g fresh blueberries",
      "2 passionfruit, halved",
      "Fresh mint leaves, to garnish",
    ],
    instructions: [
      "Preheat oven to 120C (100C fan-forced). Line a large baking tray with baking paper and draw a 22cm circle on the paper as a guide, then flip the paper over.",
      "Using electric beaters or a stand mixer, beat the egg whites on medium speed until soft peaks form. The bowl and beaters must be completely clean and grease-free or the whites will not whip properly.",
      "Gradually add the caster sugar, one tablespoon at a time, beating well after each addition. Continue beating for 10-12 minutes until the meringue is thick, glossy, and the sugar is completely dissolved. Rub a little between your fingers — it should feel smooth, not gritty.",
      "Gently fold in the cornflour, white vinegar, and vanilla extract using a large metal spoon. Be careful not to knock out the air.",
      "Spoon the meringue onto the prepared tray, using the circle as a guide. Shape into a round with slightly higher edges and a shallow well in the centre — this will hold the cream and fruit.",
      "Bake for 1 hour 15 minutes to 1 hour 30 minutes until the outside is dry and firm to touch. Turn the oven off and leave the pavlova inside with the door slightly ajar to cool completely. This prevents cracking.",
      "When ready to serve, whip the cream and icing sugar until soft peaks form. Pile the cream into the centre of the pavlova, then arrange the strawberries, kiwi, and blueberries on top. Scoop the passionfruit pulp over everything and scatter with mint leaves.",
      "Bring the whole pavlova to the table and let someone carve it — it will crack and collapse a bit, which is exactly how it should look.",
    ],
    contributedBy: "Mum",
    story:
      "Christmas Day isn't Christmas Day until the pav comes out. Mum starts it in the morning while everyone is opening presents, and it cools in the oven while the family heads to the beach. By the time lunch is done and everyone is half-asleep on the couch, she loads it up with cream and fruit and brings it out to a round of applause. There was one year the meringue collapsed completely — Dad called it a 'deconstructed pavlova' and everyone ate it out of bowls. It tasted exactly the same.",
    tags: [
      "pavlova",
      "christmas",
      "dessert",
      "meringue",
      "summer",
      "australian",
      "celebration",
      "holiday",
    ],
    featured: false,
    createdAt: "2024-12-01T10:00:00Z",
  },
];

export function getRecipeBySlug(slug: string): Recipe | undefined {
  return RECIPES.find((recipe) => recipe.slug === slug);
}

export function getRecipesByCategory(category: string): Recipe[] {
  return RECIPES.filter((recipe) => recipe.category === category);
}

export function getFeaturedRecipes(): Recipe[] {
  return RECIPES.filter((recipe) => recipe.featured);
}

export function searchRecipes(query: string): Recipe[] {
  const lower = query.toLowerCase();
  return RECIPES.filter((recipe) => {
    return (
      recipe.title.toLowerCase().includes(lower) ||
      recipe.description.toLowerCase().includes(lower) ||
      recipe.tags.some((tag) => tag.toLowerCase().includes(lower)) ||
      recipe.ingredients.some((ingredient) =>
        ingredient.toLowerCase().includes(lower)
      )
    );
  });
}
